### ISSUE TITLE
Task: Bonus einbauen für jedes abgeschlossene Tutorial video

### ISSUE THREAD

**Issue by Timkoe** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#178]
Bonus: 
-Prot II Rüstung pro tutorial vid 1 part
- Stack essen

**Comment by Timkoe** [comment]
Müssen das noch mit tutorial verbinden

**Comment by TimK1998** [comment]
UMaWfRw
MkLhNOg
uyPlslF
sfKdFdm
