### ISSUE TITLE
Task: Texture pack muss als prompt geladen werden

### ISSUE THREAD

**Issue by Timkoe** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#196]

**Comment by Timkoe** [comment]
Hilfe Mama das hängt

**Comment by Kyraja** [comment]
Also bei mir auf meinem lokalen Server funktioniert es einwandfrei... nur auf remote gehts nicht....

**Comment by TimK1998** [comment]
Jo bei mir gehts auch aufm Privaten Server. Ich teste es mal für den GameServer

**Comment by TimK1998** [comment]
Ja geht, ich schließe das dann mal.
