### ISSUE TITLE
Spieler die minimal die Kampfzone berühren können feststecken

### ISSUE THREAD

**Issue by Timkoe** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#248]

**Comment by Timkoe** [comment]
Pressure plates und tripwires können von normalos nicht ausgelöst werden

**Comment by TimK1998** [comment]
> Pressure plates und tripwires können von normalos nicht ausgelöst werden

Fixed. Fehlt nur noch das mit dem feststecken
