### ISSUE TITLE
[Class-System]/skills und /slots nicht richtig sortiert 

### ISSUE THREAD

**Issue by AioAioAio** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#281]
/skills und /slots nicht richtig sortiert

**Comment by AioAioAio** [comment]
Ist nicht gefixt 
Und ist bei jeder Klasse so

**Comment by Timkoe** [comment]
bitte überprüfen.

**Comment by TimK1998** [comment]
Ja liegt wohl an Linux, muss man mal schauen, wie man das am besten fixt
