### ISSUE TITLE
Meldung bei spawn verlassen zeigt immer 48 stunden noobschutz selbst wenn man keine 48 stunden mehr hat

### ISSUE THREAD

**Issue by AioAioAio** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#282]
Meldung bei spawn verlassen zeigt immer 48 stunden noobschutz selbst wenn man keine 48 stunden mehr hat

**Comment by Kyraja** [comment]
Bitte nochmal testen, wir können das nicht mehr nachstellen
