### ISSUE TITLE
Kettenrüstungsdrops von Mobs 50% reduzieren

### ISSUE THREAD

**Issue by Timkoe** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#315]

**Comment by TimK1998** [comment]
Vorher: Nur bei Skeletten und Zombies, Dropchance 0.5% pro Teil, 2% insgesamt

Jetzt: Alle Bosse, Dropchance 2,5% pro Teil, 10% insgesamt

Passt das @Timkoe ?

**Comment by Timkoe** [comment]
Ich bin mir nicht sicher ob die 2% drops funktioniert haben wir haben insgesamt mehrere hundert bosse gekillt und niemand hat ein teil bekommen. Testen wir es mal mit den 10%

**Comment by TimK1998** [comment]
Warn halt auch nur Zombies und Skelette
