### ISSUE TITLE
Folgendes droppt bei Sprengladung im g fight

### ISSUE THREAD

**Issue by Timkoe** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#319]
Öfen droppen items im g fight
Itemframes + items
leitern + pistons

**Comment by TimK1998** [comment]
Bitte nochmal ausführlich testen

**Comment by TimK1998** [comment]
@Timkoe Push

**Comment by Timkoe** [comment]
Itemframes mit Item drinne droppen
sonst nichts

**Comment by TimK1998** [comment]
Also Item-Frames und Pistons lassen sich nicht verhindern. Bei Fackeln ist das Problem bei mir gar nicht aufgetreten
