### ISSUE TITLE
G fight - Goldausschüttung nach win funktioniert nicht korrekt

### ISSUE THREAD

**Issue by Timkoe** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#323]

**Comment by Timkoe** [comment]
![2020-04-06_20 03 34](https://user-images.githubusercontent.com/55351056/78597875-8dcc9a80-784e-11ea-92b5-41104c7bed07.png)

**Comment by Timkoe** [comment]
Muss ggf. mehr getestet werden

**Comment by TimK1998** [comment]
Muss nochmal getestet werden

**Comment by Timkoe** [comment]
Funktioniert richtig
