### ISSUE TITLE
Arte dropt keine Items mehr nach restart

### ISSUE THREAD

**Issue by Timkoe** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#328]

**Comment by Timkoe** [comment]
Muss ggf. retestet werden

**Comment by TimK1998** [comment]
Hatte vergessen das Artefakt nach einem Kampf zu speichern. Sollte also gefixt sein, muss aber nochmal getestet werden @Timkoe .

**Comment by TimK1998** [comment]
@Timkoe  Push

**Comment by Timkoe** [comment]
@TimK1998 haben wir das jetzt gestern korrekt gecheckt? Da ging es oder?
sorry habs nicht mehr im Kopf
