### ISSUE TITLE
Schwer leserliches Startmenü?

### ISSUE THREAD

**Issue by CubexsOne** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#333]
In dem Tutorial sieht man dieses Menü.
Kommt es nur mir so vor oder liegt es auch am Shader oder ist das Gelb / Gold schwer leserlich?
<img width="325" alt="schwer leserilich" src="https://user-images.githubusercontent.com/46932387/79614692-5d63e680-8101-11ea-9fd0-46f061db8f0d.png">

**Comment by Timkoe** [comment]
Sollte ingame nicht so problematisch sein.
