### ISSUE TITLE
Zu Viel Text bei Region wechsel?

### ISSUE THREAD

**Issue by CubexsOne** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#334]
Beim verlassen der Gebiete bekommt man für MC Textbox Verhältnisse schon eine kleine Textwand ums Ohr geschmissen.

Kann man das eventuell runterkürzen?
Oder schöner Formatieren?
Also zB Absichtliche Zeilenumbrüche?
<img width="589" alt="zu viel Text 2" src="https://user-images.githubusercontent.com/46932387/79614777-8edcb200-8101-11ea-9607-1d66b261e6c2.png">

**Comment by Timkoe** [comment]
Soviel ist leider notwendig

**Comment by CubexsOne** [comment]
Dann schöner Formatieren.
Ist einfach unschön so einen Block zu lesen.
