### ISSUE TITLE
Zu viel Text bei Klassenbeschreibung?

### ISSUE THREAD

**Issue by CubexsOne** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#335]
Vielleicht kommt es nur mir so vor, aber ich wollte es dennoch anmerken.

Habe im Tutorial diese Beschreibungen gesehen und ich finde das ist too much.
Stichpunkte und etwas Farbe würde dem Auge denke ich gut tun.

- Mana
- Health

oder sowas.
<img width="557" alt="Zu viel Text" src="https://user-images.githubusercontent.com/46932387/79614895-cea39980-8101-11ea-859b-6500d56b987b.png">

**Comment by Timkoe** [comment]
Die beschreibungen müssen den Spielern die Klassen erklären.

**Comment by CubexsOne** [comment]
Dann schöner Formatieren.
Ist einfach unschön so einen Block zu lesen.
