### ISSUE TITLE
/help admin zeigt nicht die Admin commands an - Internal Server Error

### ISSUE THREAD

**Issue by Timkoe** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#341]
![grafik](https://user-images.githubusercontent.com/55351056/79691433-bfd2f900-825f-11ea-9b03-e71c7968a106.png)

Steps
- /help 
- /help admin
- Admin commands werden nicht aufgelistet, stattdessen wird Fehlermeldung angezeigt

2. Hilfe Seiten brauchen noch loca: command.help.page

**Comment by TimK1998** [comment]
Funktioniert bei mir ausgezeichnet

**Comment by TimK1998** [comment]
Scheint mit den neueren Pluginversionen schon gefixt zu sein
