### ISSUE TITLE
/skills und /slots - Skillreihenfolge falsch

### ISSUE THREAD

**Issue by minecabl** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#356]
Die Reihenfolge der Skills auf /skills und /slots sind scheinbar komplett Random, sollten eigentlich nach Level sortiert sein. 

![F0j6OEv](https://user-images.githubusercontent.com/61363659/80071422-e5ece780-8544-11ea-82a6-4db908554f6f.png)
![XQ7UKxK](https://user-images.githubusercontent.com/61363659/80071434-e8e7d800-8544-11ea-892d-a8870821e7fe.png)

**Comment by TimK1998** [comment]
Duplicate of #281 .
