### ISSUE TITLE
TnT funktioniert nicht, kann gezündet werden verschwindet allerdings dann (wildnis)

### ISSUE THREAD

**Issue by Timkoe** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#362]

**Comment by TimK1998** [comment]
Soll so sein, funktioniert nur auf feindlichem Gildengebiet.

**Comment by Timkoe** [comment]
Meinst du auf eigenem Gildengebiet?

**Comment by TimK1998** [comment]
Der Tnt als Item geht nirgendwo. Das Tnt als Command nur in feindlichem Gebiet. Ich denke ich werde noch das craften von Tnt deaktivieren.
