### ISSUE TITLE
Wenn Sprengladung auf fließendes Wasser gesetzt wird, wird das Tnt abgeschwemmt

### ISSUE THREAD

**Issue by Timkoe** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#366]

**Comment by TimK1998** [comment]
Ich denke, dass lässt sich nicht verhindern

**Comment by Timkoe** [comment]
Okay, denke es ist auch nicht allzu schlimm.
Würde das Ticket aber offen lassen, vllt können wir es in Zukunft vor 2.0 fixen.
