### ISSUE TITLE
Arena: Zuschauen

### ISSUE THREAD

**Issue by Torre1234** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#371]
Issue:
Spieler sind beim duell in eigener Instanz, um keine anderen Gegner und deren Skills zu sehen
---> auch Zuschauer sehen aktuell niemanden

Fixx:
Nur andere "Duellanten" und ihre Spells etc werden für sich im Duell befindene Spieler ausgeblendet,
 Zuschauer am Spawn können alle Spieler in der Arena sehen

**Comment by Timkoe** [comment]
Fänd ich cool. @TimK1998 machbar?
