### ISSUE TITLE
Reperatur-System: too expensive

### ISSUE THREAD

**Issue by Torre1234** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#376]
Issue:
Da wir über einen Avil reparieren speichert Minecraft die Anvilinteraktionen des Items, irgendwann wird das repairen "too expensive" obwohl wir kein LvL System nutzen.

Workaround/zusätzliches Feature:
Repairschild beim Schmied welches Gold und 2 Dias kostet und beim Rechtsclick das Item instant repariert und damit die Anvil Abfrage nach McExp ignoriert.

**Comment by Timkoe** [comment]
@TimK1998 was meinste dazu?

**Comment by TimK1998** [comment]
@Torre1234  @Timkoe  Bitte testen, ob das too expensive in vanilla auch beim kombinieren von zwei verzauberten Items kommt, bzw. ob die Anzahl der Reperaturen in Vanilla Einfluss auf die Expkosten beim kombinieren zweier enchanteter Items hat.

**Comment by Torre1234** [comment]
Ja, die Anzahl der Enchants hat sogar mehr Einfluss als die Häufigkeit der Reperaturen. Also der Fehler tritt vor allem bei Items mit vielen Enchants auf, die dann mehrfach repaired werden.

**Comment by TimK1998** [comment]
Bitte testen. Es sollte nun so sein, dass wenn man verzauberte Items repariert oder kombiniert es konstant 10 Exp- Level benötigt, und ansonsten 1 Exp-Level. Die Cap sollte nie erreicht werden.

**Comment by Timkoe** [comment]
@Torre1234 bitte Infor geben

**Comment by Torre1234** [comment]
Funktioniert wie geplant, d.h.
MC Level 30 +30 Lapis für Max Enchant
Reperatur mit gleichem Item +200g +10 MC Level
Kombination von Enchants 200g + MC Level

too expensive ist beim Testen mit höchst möglichem Enchant bei mehrfach repairen nicht aufgetreten.
Designtechnisch fände ich etwas weniger Lapis vielleicht sinnvoll, oder wir geben es in die Berufe/Arte Drops. Insgesamt fände ich einen Schmied, der vor allem Gold kostet ganz gut, und man könnte Überlegen das Repairen über Diamanten zu machen, da die Kosten aktuell stark unterschiedlich sind(aktuell bei 3 Klassen 2 Dias, Barbar 3 Dias und beim Jäger 0)

**Comment by Timkoe** [comment]
Danke. Würde sagen wir machen aus dem weiteren Feedback ein Improvement und schließen diesen Bug.
