### ISSUE TITLE
Klassensystem: Partikel, Sounds und Funktionalität aller Fähigkeiten

### ISSUE THREAD

**Issue by Vollgasidiot** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#378]
((In Doppelklammer markiert sind Fähigkeiten, die kürzlich angepasst wurden: k.A ob noch buggy)

************ Bugs/Probleme:

-Hexer-
Feuerschuss: tickt zu lange (4 Ticks statt 2)
Eisfesseln: Slow von 4sek auf 8sek, Range von 4 Blöcke auf 6 Blöcke

-Waldläufer-
((Bärenfalle: kann mehrfach platziert werden, despawnt nicht, Redstone buggt manchmal weg und liegt aufm Boden rum))

-Templer-
/

-Schattenklinge-
Ruf des Assassinen immer noch in Slotanzeige, sollt eigentlich entfernt sein

-Barbar-
Axtwurf: bekannter Bug, Axt manchmal aufsammelbar

--------------------------------------------------------------------------------------------------------------

************ Sound-/Partikelfixes:

-Hexer-
Eiskäfig: Partikel unnötig, Eiskäfig sieht man so oder so  -------DONE
Schneesturm: aktuell gar keine Partikel, vielleicht Schneepartikel mit hoher Streuung?
Zeitkrümmung: anderen Sound hinzufügen, Enderdragon death ist viel zu laut und lang 

-Waldläufer-
Stachelpfeil: paar Partikel zu viel -------DONE
Präzisionsschuss: minimal Partikel hinzufügen 
Arkaner Schuss: weniger Partikelstreuung -------DONE nochmal checken pls

-Templer-
Siegel des Zorns:  pro Spieler werden Partikel verstreut = viel zu viele Partikel => ändern auf Partikel um Anwender 	-------DONE
Heiliger Atem: 50% weniger Herzchenpartikel mit weniger Streuung -------DONE streuung ggf nochma checken
Schildstoss: Partikeleffekt um 40% reduzieren  -------DONE
Deus Vult: Partikeleffekt hinzufügen  -----DONE
Himmlische Leichtigkeit: Soundeffekt leiser  -------DONE pls checken
Gott mit Uns: Partikeleffekt auf getroffene Verbündete hinzufügen (nur minimal)  -----DONE

-Schattenklinge-
((Trittnägel: Wololo Sound entfernen/ersetzen, Partikel streuen zu weit (vielleicht Partikel nur am Boden konzentrieren, macht mehr Sinn))) -------DONE pls checken
Giftklinge: geringere Tickdauer / stärkerer Gifteffekt 
Nachthauch: 50% weniger Herzen und weniger Streuung -------DONE
Hinterhalt: Partikel auf getroffenes Ziel hinzufügen
Dolchsturz: Critpartikel zu irgendetwas geilerem ändern -------DONE pls abchecken

-Barbar-
Zyklonaxt: pro Spieler werden Partikel verstreut = viel zu viele Partikel => ändern auf Partikel um Anwender  	-------DONE
Wundsalbe: 50% weniger Herzen und weniger Streuung -------DONE
Axtwirbel: 50% weniger Partikel 
Wutsprung: Partikel beim getroffenen Ziel einbauen
Spalten: 30% weniger Partikel -------DONE
Aufstampfen: Impact aufm Boden braucht Partikel, aktuell keine vorhanden

**Comment by TimK1998** [comment]
Hab bei Axtwurf mal ein bissl was geändert, aber keine Ahnung ob es das gefixt hat. Bitte nochmal testen!

**Comment by Timkoe** [comment]
Hab meine Partikel changes mit -------DONE markiert.

**Comment by Timkoe** [comment]
Ich ändere nochmal die Partikelstreuung. (angeblich der letzte wert)

**Comment by oroshikirin11** [comment]
Ich habe gemacht:
- Präzi
- Hinterhalt
- Axtwirbel
- Wutsprung
- Aufstampfen

Bitte testen damit man sie als DONE markieren kann.
Anmerkung zu Aufstampfen:
 Block/Item cracked gibt nur verbuggte Partikel (lila)
 Wenn die Gegner hochfliegen kommt eine Art Wolke und beim landen kommen die vanilla Block    Partikel, finde es sieht trotzdem passend aus

**Comment by Vollgasidiot** [comment]
@oroshikirin11 

- Präzi stimmt so, bei nem getroffenen Gegner vielleicht noch redstone ore partikel hinzufügen? so können mates sehen, wenn man jemanden mit viel damage getaggt hat

- Axtwirbel ist zwar immer noch viel, aber denke ich in ordnung. wenn man visibility bei nem aoe spell will, dann kommt man da nicht drum rum. ist ja nur der eine skill

- Hinterhalt kann ich noch nicht gucken, brauche spieler

- Wutsprung genauso

- Aufstampfen sieht gut aus
