### ISSUE TITLE
(Improvement) Hardcode übersetzbar machen (z.B Regions, Lebensanzeige rechts etc.)

### ISSUE THREAD

**Issue by Vollgasidiot** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#386]
in messagedateien können aktuell keine regionnames etc. verändert werden

**Comment by Vollgasidiot** [comment]
+ Basic skills (Schwertschlag, Hieb etc.) können nicht verwendet werden, da der hardcode nur /skill Schwertschlag ausführt

**Comment by Kyraja** [comment]
Die Skills kannst du auch mit Zahlen casten für die Slots. Aber wir schauen mall rein :)

Die anderen zwei Sachen passen wir an :)

**Comment by Vollgasidiot** [comment]
florian pändersonne, ich rede von den basic spells, die du per rechtsklick auf die waffe ausführst. die sind standardmäßig als /skill (skillname) gesetzt. durch sprachenänderung ändert sich aber der skillname von z.b /skill schwertschlag zu /skill smite, was dann natürlich nicht funktioniert, da schwertschlag im englischen nicht genommen wird.

**Comment by TimK1998** [comment]
Man Flo..

**Comment by Kyraja** [comment]
Wer hat das denn so scheiße programmiert?
mal ehrlich @TimK1998

**Comment by Vollgasidiot** [comment]
Feuergeschoss (Hexer) läuft noch nicht

Mana ist auch noch hardcode
