### ISSUE TITLE
[Command] Unsichtbare Spieler auf regenrierten Chunks

### ISSUE THREAD

**Issue by oroshikirin11** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#388]
Wenn ein Admin mit /admin regenerate einen Chunk regenriert, werden Spieler welche auf diesen laufen unsichtbar.

**Comment by Timkoe** [comment]
nicht 100%

**Comment by TimK1998** [comment]
Ist wenn dann eh ein Bug von Spigot, lässt sich also nicht fixen.
