### ISSUE TITLE
MEHR Schutzzeit erhalten

### ISSUE THREAD

**Issue by Timkoe** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#390]
Schutzzeit bei Niederlage allgemein auf 12H erhöhen.
Schutzzeit bei Gewonnener Verteidigung auf 4H.

**Comment by TimK1998** [comment]
Was ist "Norm". Sowas existiert im Elo System nicht. Wenn überhaupt -> 2.0

**Comment by Timkoe** [comment]
Norm = Startwert

**Comment by Timkoe** [comment]
5h die wir im Moment haben sind zu wenig für Noobgilden

**Comment by TimK1998** [comment]
Macht trotzdem keinen Sinn. Wenn die von besseren Gilden angegriffen werden verlieren die kaum Elo, d.h. der Schutz würde nie greifen.

**Comment by TimK1998** [comment]
Das an Elo festzumachen ist dumm, weil Elo in keiner Weise linear ist, sondern sowohl vom ANgreifer als auch vom Verteidiger abhängt.

**Comment by TimK1998** [comment]
Wenn überhaupt müsste man das an Elodifferenzen festmachen, z.B. hat Angreifer x Elo mehr als Vertidiger, dann addiere y Stunden auf die Schutzzeit

**Comment by TimK1998** [comment]
Dabei ist aber das Problem, dass schwer zu sagen ist, wie gut eine Gilde tatsächlich ist. Gewinnt bspw. die Übergilde mit 1800 Elo gegen eine sau starke Gilde mit 1400 Elo, würde für die sau starke Gilde dann trotzdem der Noobbonus greifen --> Das am Elo System festzumachen funktioniert vorne und hinten nicht, egal was man sich überlegt.

**Comment by Timkoe** [comment]
Der Noob bonus würde nur greifen wenn der Elo Wert kleiner als der Startwert ist und die Gild somit schlechter als der Durchschnitt ist.
Wenn ne 1400 Gilde gegen eine 1800 Gilde gverliert würde das die Schutzzeit überhaupt nicht beeinflussen.
Unter 1000 + 2 Stunden
900 Elo + 2 Stunden
800 Elo + 2 Stunden

Klar hängt die gesammelte Elo immer vom Gegner ab aber Gilden die unter dem 1000 Wert sind sind definitiv keine krassen Gilden und somit würde der Extra Schutz nie die falschen treffen.

**Comment by TimK1998** [comment]
Es ist aber halt wirklich falschrum. Wenn du gegen schlechte Gilden verlierst sinkt deine Elo krass -> Potentiell mehr Schutzzeit.
Wenn du gegen starke Gilden verlierst sinkt deine Elo kaum/evtl. sogar gar nicht -> Kaum Bonus auf Schutzzeit.

Das macht einfach keinen Sinn, da musst du dir einfach was besseres einfallen lassen, bevor ich so nen Quatsch aufwenig umsetze nur um ihn dann in einer Version wieder zu ändern weil jemandem was besseres eingefallen ist.

**Comment by TimK1998** [comment]
Es ist halt sogar so, dass wenn eine Gilde über 1400 Elo hat und die andere 1000, dann verliert die Gilde mit 1000 Elo 0 Elo, würde also nie in den Bereich der Bonusschutzeit fallen und könnte andauernd geraidet werden

**Comment by TimK1998** [comment]
Außerdem würde man schwache Gilden, die auf höhere Schutzzeiten angewiesen sind bestrafen, wenn die sich Mühe geben und gegen eine starke Gilde gewinnen, da die dann richtig viel Elo bekommen und ihre Bonusschutzeit weniger wird. 
Also um klar zustellen: Ich bin auch für höhere Schutzzeiten, aber nicht nach diesem Konzept.

**Comment by oroshikirin11** [comment]
Mit fällt auf die Schnelle leider nichts ein aber denkt ihr auch mal über eine Alternative nach, so ein Feature ist meiner Meinung nach eines der wichtigsten damit die Versionen eine längere Lebenszeit haben.

**Comment by Timkoe** [comment]
Können uns heute abend was zusammen überlegen.

**Comment by Kyraja** [comment]
Und was ist das Ergebnis jetzt ? :)

**Comment by Timkoe** [comment]
Das was ganz oben im Ticket steht :)
