### ISSUE TITLE
Gilden werden aktuell falsch als Offline gewertet

### ISSUE THREAD

**Issue by Timkoe** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#399]
Aktuell zählt alles unter 3 Membern online als Offline.

Im Konzept so definiert:
"Für einen Gildenkampf müssen online sein:

Gilde unter 4 Member = 1    Gilde ab 4 Member = 2  Gilde ab 8 Member: 3 |  
-- | --
- Es können immer nur 2 Gilden am Gildenkampf beteiligt werden (Angreifer und Verteidiger) |

**Comment by TimK1998** [comment]
Bitte nochmal testen @Timkoe . Es hat gerade bei privaten Tests den Eindruck gemacht, dass es funktioniert
