### ISSUE TITLE
Vote Benachrichtigungen designen

### ISSUE THREAD

**Issue by TimK1998** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#402]

**Comment by Timkoe** [comment]
Für message wenn keiner votet
Für message wenn spieler gevotet haben

**Comment by Timkoe** [comment]
![lkvote](https://user-images.githubusercontent.com/55351056/80862260-e8052380-8c73-11ea-979f-b52d11f797d5.png)
![lkvote2](https://user-images.githubusercontent.com/55351056/80862261-e9cee700-8c73-11ea-9736-1ff326eedc31.png)

**Comment by TimK1998** [comment]
Nachrichten umgesetzt. Allerdings noch nicht klickbar.
