### ISSUE TITLE
Gildenblock kann im G fight wegen Adventure mode nicht abgebaut werden

### ISSUE THREAD

**Issue by Timkoe** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#405]

**Comment by Kyraja** [comment]
@TimK1998 ist es nicht so dass wir kein Block Click Event haben im Adventure Mode?

**Comment by TimK1998** [comment]
@Kyraja Das ist korrekt, deswegen hab ich dafür jetzt ein workaround gemacht. Ist also schon gefixt, habs nur noch nicht gepusht.

**Comment by Timkoe** [comment]
Passiert imernoch
