### ISSUE TITLE
[Artefakt] Items im Menü über den Gildenblock abholbar machen

### ISSUE THREAD

**Issue by Timkoe** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#411]
Items im Menü über den Gildenblock abholbar machen
Die Gilde die das Artefakt besitzt sollte die Items aus dem Gildenblock holen können.

**Comment by Timkoe** [comment]
Double checke das

**Comment by TimK1998** [comment]
Habs gerade getestet scheint gut zu funktionieren

**Comment by Timkoe** [comment]
Sind die drops ok? / nicht zu viel?

**Comment by TimK1998** [comment]
Denke das passt aber kp

**Comment by TimK1998** [comment]
Die Toolwahrscheinlichkeit find ich aber zu krass, der Rest darf gerne höher

**Comment by TimK1998** [comment]
![Unbenannt](https://user-images.githubusercontent.com/7693029/80960059-62ff4300-8e08-11ea-969b-4a8b9aaf56cb.PNG)

Nach ca 4 Stunden

**Comment by TimK1998** [comment]
Wobei man sagen muss das es im Durchschnitt in der Zeit eigentlich ja nur 4 Tools sind, aber 1 pro Stunde ist trotzdem nicht wenig

**Comment by Timkoe** [comment]
Das ist denke ich zu krass, wir müssen bedenken, dass Gilden das 7 Tage bis zu nächsten Reset haben. 
Das gäben 168 Waffen und Tools, das ist too much.
Ich würde sagen: 2 Waffen und 2 Tolos in 24H

Der Rest sollte okay sein.

Wird das Gold richtig auf die Schatzkammer überwiesen? @TimK1998

**Comment by Torre1234** [comment]
Würde auch sagen ist deutlich zu viel, lieber zu Release etwas zu weak als dass wir economy zerstören und Leuten im worst case ihre arte drops weg nehmen müssten wenn es zu stark wäre. Finde die Drops insgesamt fine wenn man Tools etwas nerft, ist halt auch die Frage wie lange man das Arte halten kann. Können Gilden mit dem Arte Schutzzeit bekommen? Und bekommt man lapisblöcke? Wäre bei unserem System denke ich reizvoller als redstone blöcke mit denen 90% eh nichts anfangen können

**Comment by TimK1998** [comment]
Jo hab die Wsk für Waffen/Tools angepasst, dass mit dem Gold müsste nochmal jemand testen

**Comment by Timkoe** [comment]
Funktioniert alles nur das Gold kommt noch nicht in die Schatzkammer / ins Inv laut Kamu
(Haben ein paar Stunden gewartet)
@TimK1998

**Comment by oroshikirin11** [comment]
Obsidian Drops bitte um die Hälfte reduzieren

**Comment by TimK1998** [comment]
Obsidian angepasst, Gold hat bei mir Problemlost funktioniert.
