### ISSUE TITLE
[Ränge] Ergebnisse der permissions tests

### ISSUE THREAD

**Issue by oroshikirin11** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#420]
Support
- kann nicht in gm3
- kann keinen tempbannen
- Kein Command für guild name change
- Kein Command für Streamer mode
- Kein Command für spectate

**Comment by Timkoe** [comment]
Player:
- Kann nicht auf settings -> somit Sprache nicht wechseln

**Comment by TimK1998** [comment]
Hat perfekt funktioniert bei privaten Tests:
/g rank funktioniert nicht für spieler (interner fehler)
Gildenränge können nicht über den Gildenblock verändert werden -> nichts passiert bei klick

Kann nicht auf settings -> somit Sprache nicht wechseln
Ist so gewollt. Das settings Menü hat keinen Zweck. Sprache wird man über Cmd ändern können

Wird es nicht geben: 
kann nicht in gm3
kann keinen tempbannen
Kein Command für guild name change
Kein Command für Streamer mode

Wird noch eingebaut
Kein Command für spectate

**Comment by Timkoe** [comment]
retesten das mit den gildenrängen pls.
