### ISSUE TITLE
[Teleport] Du wurst in 0 Sekunden teleportiert

### ISSUE THREAD

**Issue by Timkoe** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#423]
https://images-ext-2.discordapp.net/external/XhY1N-BysAyJj5mZgfRDpWDHKUjWUGfNOfhzJWHYrys/https/i.badlion.net/oqvNp7w8rMFQQ3V94ZXtM4.png?width=1204&height=677

TP countdown für porter scuffed,
Tippfehler in der Message

**Comment by TimK1998** [comment]
Beides Tippfehler in der Message
