### ISSUE TITLE
G list funktioniert noch nicht / Hat noch keine Liste 

### ISSUE THREAD

**Issue by Timkoe** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#425]
![grafik](https://user-images.githubusercontent.com/55351056/80872458-61236b80-8cb2-11ea-9ce1-df863b7e5641.png)

**Comment by Kyraja** [comment]
Wie soll er genau aussehen? Aktuelle bedeutet die Meldung oben, dass die Message noch fehlt. Als Parameter bekommt ihr den Gildennamen :)

**Comment by TimK1998** [comment]
Jo @Timkoe hau mal nen design für das Menü raus.

**Comment by Timkoe** [comment]
Yo yo yo @TimK1998  ich hau mal nen Design raus skrrrrrrrrrrrrrrrrrrrrrrrrrrr
![glist](https://user-images.githubusercontent.com/55351056/80894004-50d1b780-8cd7-11ea-8f87-9e4aa4595015.png)

Gilden sind selbstverständlich warheitsgetrau angeordnet.

**Comment by TimK1998** [comment]
@Timkoe Bitte testen, ob die Liste aufwärts oder abwärts sortiert.

**Comment by Timkoe** [comment]
![tabliste](https://user-images.githubusercontent.com/55351056/80915981-0ba09a80-8d56-11ea-9244-a1d324366ec9.png)

**Comment by Timkoe** [comment]
![grafik](https://user-images.githubusercontent.com/55351056/81008091-9a92dd00-8e52-11ea-99c2-82ec53584e4e.png)
fast perfekt nur bitte andersrum sortieren lassen (abwärts)

**Comment by TimK1998** [comment]
Sollte schon gefixt sein
