### ISSUE TITLE
Help Command aktualisieren und Commandbeschreibungen einfügen

### ISSUE THREAD

**Issue by TimK1998** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#428]

**Comment by Timkoe** [comment]
Bitte sämtliche neuen Commands mir geben.
zb. vote, lotterie,  admin cmds
premium usw

**Comment by TimK1998** [comment]
Du musst eh alle Commands nochmal durchgehen, weil du für die hälfte keine Descriptions erstellt hast.

**Comment by Timkoe** [comment]
@oroshikirin11 @VMMarco könnte das vllt einer von euch carrien?

**Comment by oroshikirin11** [comment]
Ich mach das dann mal

**Comment by oroshikirin11** [comment]
Alle Admin Commands haben eine Beschreibung im Code.
Alle nicht-Admin Commands haben eine deutsche Übersetzung.
