### ISSUE TITLE
Neue Commands ins Wiki eintragen

### ISSUE THREAD

**Issue by TimK1998** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#429]

**Comment by Timkoe** [comment]
Bitte sämtliche neuen Commands mir geben.
zb. vote, lotterie, admin cmds
premium usw

**Comment by Timkoe** [comment]
@VMMarco @oroshikirin11 da seid ihr dran richtig?

**Comment by oroshikirin11** [comment]
Team Commands-------------------------------------------
/admin abort
/admin addmoney <value>
/admin artefact start
/admin ban <player> <reason>
/admin clear
/admin debug
/admin disband <guildname>
/transaction <player>
/admin friendly <player>
/admin expboost <minutes> <boost>
/gamemode <gamemode> <player>
/admin global <time> <message>
/admin globalmute
/admin invclear <player>
/admin invsee <player>
/admin kick <player> <reason>
/admin mute <player>
/admin premium <premiumtype> <player>
/admin premium generate <premiumtype> <amount>
/admin regenerate
/admin removemoney <player> <amount>
/admin resetcd <player>
/admin reset <player>
/admin resetmana <player>
/admin restart
/admin stop
/admin spectate <player>
/admin setrank <player> <rank>
/tp <player1> <player2>
/admin tempban <player> <time> <reason>
/admin tempmute <player> <minutes>
/admin unban <player>
/admin unmute <player>
/admin vanish

**Comment by oroshikirin11** [comment]
Habe dir die Commands mit Parameter über Discord geschickt.
