### ISSUE TITLE
/pvp <Zone> Command einfügen 

### ISSUE THREAD

**Issue by TimK1998** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#430]

**Comment by Timkoe** [comment]
Wäre dagegen die paar Meter kann man laufen und wäre auch nicht so nice wenn der Gegner den du eben gekillt hast sich instant wieder ranportet und dich auf lowlife absnackt.

**Comment by oroshikirin11** [comment]
fände ich auch nicht so nice tbh.
Es hat was taktisches wenn man laufen muss
