### ISSUE TITLE
Streamer Support- Folgendes für den Rang Content Creator ermöglichen:

### ISSUE THREAD

**Issue by Timkoe** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#432]
Streamer Support- Folgendes für den Rang Content Creator ermöglichen:
Um etwas Streamer freundlicher zu werden

/blockmessages  -> Blockiert eingehende Pms, und gibt Nachricht zurück: Der Spieler hat aktuell den Streamer Modus aktiviert und kann im Moment keine persönlichen Nachrichten lesen.

reservierter Slot für die Content Creator Rolle.

**Comment by TimK1998** [comment]
Ich denke es wäre auch fein, wenn jeder den /blockmessages Command hat oder?

**Comment by TimK1998** [comment]
Das mit dem Slot ist done. Machst du den Command @Kyraja ?
