### ISSUE TITLE
Server Modt designen/Tab Liste oben und unten designen/überarbeiten

### ISSUE THREAD

**Issue by TimK1998** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#433]

**Comment by Timkoe** [comment]
![tabliste](https://user-images.githubusercontent.com/55351056/80915996-2246f180-8d56-11ea-9266-7f3942d5a76a.png)

**Comment by TimK1998** [comment]
Man kann die Tab liste nicht sortieren... Ich meinte eigentlich auschlißlich das Zeug unten und oben

**Comment by TimK1998** [comment]
Und die Server Modt ist das was in der Serverliste angezeigt wird.

**Comment by Timkoe** [comment]
Modt: 
Lost-Kingdoms.com | Guild-PvP | Klassen | Season 1

**Comment by Timkoe** [comment]
![LK-splah image_FINAL](https://user-images.githubusercontent.com/55351056/80920838-b030d580-8d72-11ea-9936-7413c8ea2b89.png)
