### ISSUE TITLE
Belagerungsbrücke

### ISSUE THREAD

**Issue by Torre1234** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#434]
Belagerungsbrücke despawned direkt nach dem Anwenden und baut sich nicht aus.

**Comment by Timkoe** [comment]
Config sollte stimmen ^^ weiß nicht woran das liegt

**Comment by Torre1234** [comment]
Gestern Abend auf dem Testserver noch aufgetreten, wurde sicher gepusht? Sonst pls nochmal testen heute
