### ISSUE TITLE
Task: Alle Commands im Plugin durchgehen und checken ob der richtige Permissionwert angegeben ist

### ISSUE THREAD

**Issue by Timkoe** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#442]

**Comment by Timkoe** [comment]
done? results? @oroshikirin11

**Comment by oroshikirin11** [comment]
Da ich jetzt die Liste habe werde ich nochmal durchgehen.
Habe meine Results vom letzten mal schon vergessen lol

**Comment by oroshikirin11** [comment]
Ein paar Sachen stehen schon in einer anderen Massenissue von mir, schreibe mehr als Kommentar hier rein.

**Comment by oroshikirin11** [comment]
Sollte jetzt alles so sein wie es sollte, es bestehen nurnoch die Fehler von meiner anderen Sammelissue.
Für so einen kack bastel ich mir ein Skript :D
