### ISSUE TITLE
Spieler können nciht in lokal / support chat channels wechseln - keine permissions egal weleche usergroup

### ISSUE THREAD

**Issue by Timkoe** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#443]

**Comment by Kyraja** [comment]
Kommt hier eine Meldung: "keine Permission" oder was passiert genau?

**Comment by Timkoe** [comment]
@oroshikirin11 was wurde dir da angezeigt?

**Comment by oroshikirin11** [comment]
Sollte doe Permission Meldung gekommen sein
Aber kann es nochmal testen

**Comment by oroshikirin11** [comment]
![perms ch](https://user-images.githubusercontent.com/16406138/81171141-2ebc8b80-8f9c-11ea-8cf5-89e8104a8bb7.PNG)
