### ISSUE TITLE
Verschiedene Issues  Player / Gilden / LOCA / Pferde

### ISSUE THREAD

**Issue by oroshikirin11** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#446]
PLAYER----------------------------------
- Wenn man auf den Server joint hat man nicht autom. den PLAYER rank ----DONE

- Player ist standardmäßig in Globalchat (richtig so) aber kann nicht mit /ch in: private chat, local chat und support chat, wechseln. Evtl. kann man auch nicht in den global chat wechseln ----DONE

ÜBERSETZUNG------------------------
- /protection show , gibt aus noob.protection.failed   ----DONE
- Übersetzung für gründen einer neuen Gilde mit dem Namen einer bereits existierenden ist nicht übersetzt ----DONE

GILDE--------------------------------------

- Option Im Gildenblock zum Namen ändern klappt nicht, sobald man den gewünschten Namen abschickt, kommt eine Nachricht welche sagt man müsse dafür an den Spawn ----DONE

- g inspect hat keine Funktion (getestet von g leader)   ----DONE

- Man kann Lapis Blöcke auf dem Gildengebiet platzieren (sollte normal nicht mögl. sein) ----DONE

SONSTIGE---------------------------------------------
- Man kann Shulker Boxen craften und platzieren (sollte normal nicht mögl. sein) ----DONE
- Als Player kann man /pl machen 

PFERDE----------------------------
- Irgendwie kann man Pferde duplizieren, wir konnten es nur nicht reproduzieren

**Comment by Timkoe** [comment]
@Kyraja @TimK1998 
Da das hier eine umfangreiche Liste ist bitte immer mit 
---DONE editieren wenn element fertig ist.
----NEED INFO wenn etwas nicht klar ist

**Comment by TimK1998** [comment]
Hab das mit dem /pl gefixt, war ja soweit ich das gesehen habe das letzte hier. Das mit den Pferden kann ich jetzt halt nicht nachvollziehen.
