### ISSUE TITLE
Combatlog spieler stirbt nicht

### ISSUE THREAD

**Issue by Tysaby** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#447]
Tötet man den villager eines ausgeloggten spielers droppen zwar seine items , jedoch ist der spieler nach dem erneuten einloggen immernoch an der alten position.

**Comment by Timkoe** [comment]
Aktuell spawnt kein Villager bei ausloggen.

**Comment by Kyraja** [comment]
@Timkoe Diese Aussage bringt mir genauso viel wie "geht nicht".... Wo ist die Beschreibung? Was habt ihr gemacht? Wie sah eurer Bildschirm aus? Wie weit standed ihr weg? Auf welcher Region standed ihr ? ..............................
Bitte beschreibt was ihr gemacht habt und macht hier Bild rein, sonst kann ich die Sachen nicht bearbeiten.

**Comment by Kyraja** [comment]
Ps... Ich kopier das jetzt nicht in jeden Issue rein....

**Comment by Timkoe** [comment]
Wir haben uns beide im gamemode 0 in der Wildnis geschlagen. Icecookie hat sich ausgeloggt und kein NPC ist aufgetaucht. Genauso auch anders herum. Wir haben es in einer Gilde und ohne eine Gilde versucht. wir standen direkt nebeneinander

Wovon sollen wir bitte ein Bild anhängen?!?

**Comment by Kyraja** [comment]
Von deinem Bildschirm... Ein Bild wo du den Spieler siehst vor dem Ausloggen (auf beiden Seiten) und dann eins nach dem Ausloggen...

Wie ich geschrieben habe, kann ich den Fehler nicht nachvollziehen und "es geht nicht" hilft mir bei der Suche nicht. Da das spawnen an Dinge wie (Noobschutz/Region/Abstand zum Spieler/Friendly) hängt brauch ich da etwas mehr Infos.

**Comment by Timkoe** [comment]
Wie gesagt, wir standen direkt einender gegenüber. Region: Wildnis
Kein friendly aktiv, beide konnten sich schlagen und gegenseitig skills einsetzen. 
Noobschutz aktiv. 

Ich versteh nicht ganz was du damit willst. Vorher siehst du eben wie er direkt vor mir steht danach siehst du ihn nicht mehr weil er sich ausgeloggt hat .. können dir aber gerne screenshots anhägen

**Comment by Kyraja** [comment]
> 
> 
> Wie gesagt, wir standen direkt einender gegenüber. Region: Wildnis
> Kein friendly aktiv, beide konnten sich schlagen und gegenseitig skills einsetzen.
> Noobschutz aktiv.
> 
> Ich versteh nicht ganz was du damit willst. Vorher siehst du eben wie er direkt vor mir steht danach siehst du ihn nicht mehr weil er sich ausgeloggt hat .. können dir aber gerne screenshots anhägen

Ganz einfach. Ich krieg den Fehler nicht hin. Also liegt es entweder an: Noobschutz, Region, Abstand, Friendly oder Gamemode... denn diese Eigenschaften führen zum Abbruch der Spawnfunktion. Daher müssen alle diese 5 Dinge ausgeschlossen werden. Und das kann ich nicht wenn ihr es wie oben beschreibt :)

**Comment by Timkoe** [comment]
Ok dann lass uns das zusammen heute abend nochmal reproduzieren :)

**Comment by oroshikirin11** [comment]
stimmt an Noobschutz könnte es gelegen haben

**Comment by Timkoe** [comment]
Warum soll denn bei Noobschutz kein NPC spawnen, denn kill sollte man ja dennoch kriegen auch wenn kein Loot gedroppt wird
