### ISSUE TITLE
Combatlog item drop issue

### ISSUE THREAD

**Issue by Tysaby** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#448]
wie es reproduzierbar ist:
1. combatlog --> villager durch end portal schieben
2.spieler loggt sich wieder ein
3. villager steht immernoch im end countdown ist angehalten , villager killen
4. spieler loggt sich wieder aus --> items droppen in  dem moment wo sich der spieler ausloggt , an der alten position in der overworld

**Comment by Timkoe** [comment]
Aktuell spawnt kein Villager bei ausloggen im Kampf
