### ISSUE TITLE
combatlog region bug 

### ISSUE THREAD

**Issue by Tysaby** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#450]
loggt man sich in der overworld aus und schiebt den villager ins endportal , so despawnt der villager bei erneutem login nicht und der spieler wechselt dauerhaft zwischen den 2 regionen end und wildnis selbst wenn der villager im nachhinein getötet wird

**Comment by Timkoe** [comment]
Aktuell spawnt kein Villager bei ausloggen im Kampf
