### ISSUE TITLE
Task: Vote Verlinkung und reward einbauen

### ISSUE THREAD

**Issue by Timkoe** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#453]

**Comment by TimK1998** [comment]
Ähm @Kyraja , ich bin mir ehrlichgesagt unsicher. Wie genau hast du dass den jetzt mit den Links umgesetzt?
In der Vote Nachricht steht nämlich z.B. nur "Klicke <<Hier>> um zur Voteseite zu gelangen". Wie genau soll ich dem <<Hier>> denn jetzt einen Link hinterlegen?

**Comment by Kyraja** [comment]
@TimK1998 Geht so nicht. Ich Parse links direkt in der Nachricht. <<Klick>> kann ich nicht parsen und das umzubauen wäre mega aufwendig. Daher würde ich erstmal vorschlagen den link reinzumachen @Timkoe

**Comment by Timkoe** [comment]
okay dann den link einfach 
am besten bauen wir dann auf die website ne übersicht ein
zb. vote.lostkingdoms oder so
