### ISSUE TITLE
[Gilden] Gilden werden manchmal nicht korrekt gelöscht bei /info

### ISSUE THREAD

**Issue by oroshikirin11** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#457]
Gilden werden manchmal nicht korrekt gelöscht bei /info
Auf dem Dev. Server wurde eine Gilde: TestGilde ,laut Chatmessage! gelöscht wegen der Obsidiansteuer
Laut /g list, TAB und /info exisitiert die Gilde noch also ist evtl. die Message falsch oder das Löschen klappt nicht so.

**Comment by Kyraja** [comment]
@oroshikirin11 Könntet ihr das nochmal bitte prüfen? Bitte mit Schritt für Schritt Anleitung. Weil bei mir hat es gestern einwandfrei funktioniert.
Auch bitte ein Bild machen, wie die Tablist & /g info & /info aussieht :) Und die Nachricht beim löschen natürlich.

Danke

**Comment by oroshikirin11** [comment]
Keine Ahnung wie ich die Obsidian Steuer triggern kann.
Kann auch sein das ich falsch geguckt hab, war spät in der Nacht :D

**Comment by TimK1998** [comment]
Habe den Fehler gefunden. Die Gilde wird erst aufgelöst, wenn sie drei Tage hintereinander nicht zahlen kann. Die Nachricht mit dem Disband ist aber nicht mit in der if tage==3 Bedingung gewesen, weswegen fälschlicherweise die Nachricht ausgegeben wurde.
