### ISSUE TITLE
[Message Channel] Man kann nicht in den Support Chat schreiben

### ISSUE THREAD

**Issue by oroshikirin11** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#458]

**Comment by oroshikirin11** [comment]
ACHTUNG:
Habe bemerkt ich kann generell nichts in den Chat schreiben, sogar mit meinem multiacc.
Evtl. wird globalmute nicht richtig aufgehoben?

**Comment by Kyraja** [comment]
@Timkoe  An wen sollen die Nachrichten im Support Channel gehen? An alle Teammitglieder? Sollen das alle im Channel sehen die grad drin sind?

**Comment by Kyraja** [comment]
@oroshikirin11 @VMMarco  Zur Übung um sich mit dem Chatsystem auseinander zu setzen dürft ihr das machen :) Ihr müsst im Channel des Support dann die Methode für die Userliste befüllen anhand der Logik die @Timkoe vorgibt

**Comment by Timkoe** [comment]
Die Nachricht soll an alle Supports & Mods gehen (auch die die nicht im channel sind)  und an alle die den Channel gerade aktiv haben.
Vielleicht gibt es ja auch normale User die die Frage beantworten können.

**Comment by oroshikirin11** [comment]
Ist auf dev server gepusht
Bitte einmal testen :)
