### ISSUE TITLE
[Guild] /g inspect funktioniert nicht?

### ISSUE THREAD

**Issue by oroshikirin11** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#460]
/g inspect funktioniert nicht?
Bei mir kommt nichts wenn ich Blöcke Rechts bzw. Linksklicke

**Comment by Timkoe** [comment]
was soll g inspect sein? ^^

**Comment by TimK1998** [comment]
Funktioniert bei mir einwandfrei

**Comment by Timkoe** [comment]
Pls nochmal testen

**Comment by oroshikirin11** [comment]
Funktioniert jetzt
