### ISSUE TITLE
[Command] /blockmessages wird nicht erkannt (getestet auf devserver ohne map)

### ISSUE THREAD

**Issue by oroshikirin11** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#461]

**Comment by TimK1998** [comment]
Da ist das Plugin nicht aktuell

**Comment by Timkoe** [comment]
Dann bitte Plugin updaten und retesten.

**Comment by oroshikirin11** [comment]
/tell blockiert er zuverlässig
Übersetzungen fehlen auch aber habe ich geadded
/msg muss entfernt werden

Und wäre niche wenn man mit /r Nachricht     antworten könnte

**Comment by Kyraja** [comment]
@oroshikirin11 Du darfst :) 1x /r einbauen und /msg disabeln :)

**Comment by TimK1998** [comment]
msg disablen könntest du glaube ich schon wenn du hinten im/tell Command aliases = {msg} einfügst

**Comment by oroshikirin11** [comment]
Ich setz mich da jetzt mal ran

**Comment by oroshikirin11** [comment]
/r ist gepusht
pls reviewen

**Comment by Timkoe** [comment]
pls nochmal code checken @TimK1998 @Kyraja
