### ISSUE TITLE
Wutsprung/Hinterhalt trifft Mobs --> ohne Effekt

### ISSUE THREAD

**Issue by Vollgasidiot** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#467]
Die Skills können Mobs targetten, erhalten auch Cooldown, jedoch wird man nicht zum Ziel teleportiert.

Entweder der skill sollte ausschließlich spieler targetten können, oder gegen mobs gleichermaßen wie auf spieler funktionieren

**Comment by Torre1234** [comment]
Hat eigentlich auf Mobs und Spieler gleich funktioniert, Region/Server?

**Comment by Vollgasidiot** [comment]
Wildnis, standardtestserver (der mit 12345679 slots)
