### ISSUE TITLE
Combatlog: Spieler erhalten keinen Kill bei Kill eines NPCs

### ISSUE THREAD

**Issue by Timkoe** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#468]
Found
Spieler erhalten keinen Kill bei Kill eines NPCs

Steps
- 2 Spieler kämpfen in der Wildnis (mit oder ohne Noobschutz egal)
- Spieler 2 loggt sich aus, villager erscheint
- Spieler 1 killt den Villager -> kein kill
- Spieler 2 loggt sich ein und stirbt
- Spieler 1 kriegt keinen Kill für Spieler 2

**Comment by Kyraja** [comment]
@TimK1998 
Kannst du dir das mal anschauen? Ich weiß nicht ganz wie du das mit den kills machst. Ich trigger aufjedenfall beim joinen das EntityDeathEvent dadurch das ich den Player mit max damage kille

**Comment by TimK1998** [comment]
Der Statistik Listener hört nur
