### ISSUE TITLE
Exp Boost werte korrekt im Code und im Shop eintragen

### ISSUE THREAD

**Issue by Timkoe** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#469]
Exp-Boost Global | Monster geben für den ganzen Server 50% mehr Exp für 60 Minuten
Gold Boost Global | Monster droppen für den ganzen Server 50% mehr Gold für 60 Minuten

Exp banner regional | monster geben im radius von 250 blöcken 50% mehr exp für 60 min
Gold banner regional | monster geben im radius von 250 blöcken 50% mehr exp für 120 min

**Comment by Timkoe** [comment]
Weiterer Change:
Premium Silber nur regionale statt globale Boosts
- 1x Exp-Boost Regional
--
- 1x Gold Boost Regional

**Comment by TimK1998** [comment]
Warum ändern denn immer Sachen ohne euch darüber Gedanken zu machen? Ich meine was hat euch denn dazu bewegt den Radius auf 250 zu ändern? 150 deckt schon ne riesige Levelfläche ab. Nur mit "Bauchgefühl" macht es keinen Sinn spielentscheidente Änderungen vorzunehmen, und wenn ihr es euch halt nicht vorstellen könnt -> Ingame testen

**Comment by TimK1998** [comment]
Das selbige bei dem ganzen Kisten und Dietrich Kram. Da werden einfach Werte festgelegt und Änderungen gemacht nur weil man das Gefühl hat, das passt nicht. Wie wäre es denn zur Abwechslung mal, dass man sich darüber a) sinnvoll Gedanken macht und b) wenn man sich nicht sicher ist, einfach mal nachrechnet. Das mit den Kisten ist ein riesiges durcheinander. Maximal baubare Kisten abhängig von Gildengröße -> Schaded kleinen Gilden. Maximal knackbare Anzahl von Kisten abhänig von maximalen Kisten -> MAcht überhaupt keinen Sinn, wenn man diese maximale Anzahl an Kisten gar nicht knacken kann weil der CD von Dietrich zu hoch ist. Da ist ganz ehrlich muss ich mal sagen fast nichts durchdacht, einfach alles nur weil man denkt, so könnte es besser sein oder so gefällts mir besser. Hättest du mal dir überlegt wie viele Leute bei einem durschnittlichen Angriff dabei sind und wie viele davon durchschnittlich Dietrich mitnehmen können, dann wärst du relativ schnell darauf gekommen, dass selbst 30% raiden beim aktuellen System eher unwahrscheinlich ist.
Ich würde ganz ehrlich vorschlagen macht euch doch nochmal Gedanken darüber und überarbeitet das Kistenknacksystem nochmal komplett. Mein erster Vorschlag:
Jede Gilde kann 30 Kisten verschließen (Warum auch nicht?). Davon kann man nur X% knacken. CD von Dietrich ist dann ungefähr so angepasst, dass man Y Spieler mit Dietrichen braucht um X% der 30 Kisten zu knacken. Ergo: Einfaches, durschaubares, vorhersehbares und gut einstellbares System, bei dem keine Gildengrößre bevor- oder benachteiligt wird. 
Da gibt es bestimmt auch bessere Lösungen, aber das aktuelle System ist einfach zusammengewürfeltet Nonsense-Müll.

**Comment by TimK1998** [comment]
@Timkoe

**Comment by Timkoe** [comment]
WTF.

Die Range sollte nie geändert werden, das war der ursprüngliche Wert, der einfach schon immer im Konzept stand. Du hattest damals 150 im Code eingetragen, da due gesehen hast die Range ist mit 150 ausreichend, es wurd bisher einfach nicht im Konzept geändert ...

Auf die Kisten issue gehe ich hier nicht ein. Siehe Dietrich.

**Comment by Timkoe** [comment]
Also hier die aktuellen und korrekten Werte (genauso wie auch vorab besprochen):

Exp banner regional | monster geben im radius von 150 blöcken 50% mehr exp für 60 min | 6.99€
-- | -- | --
Gold banner regional | monster geben im radius von 150 blöcken 50% mehr exp für 120 min | 6.99€

Ich muss es noch im Shop umtragen.

**Comment by TimK1998** [comment]
Hatten wir uns nicht auf 4,99 geeinigt?

**Comment by Timkoe** [comment]
ja sind 4.99 steht falsch im konzept aber richtig im shop sry

**Comment by TimK1998** [comment]
Okay, dann ist das jetzt alles angepasst. Zumindest im Plugin.

**Comment by TimK1998** [comment]
Gold global: 60m, x1.5
Gold regional: 120m, x1.5
Exp global 60m, x1.5
Exp regional 60m, x1.5

**Comment by Timkoe** [comment]
Habe die werte korrekt in den Shop eingetragen
