### ISSUE TITLE
Balancing: Dietrich hat jetzt 240s cooldown

### ISSUE THREAD

**Issue by Timkoe** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#470]
plsändern

**Comment by TimK1998** [comment]
WTF 240s? Wieso das denn, damit kann man ja gerade mal zwei Kisten pro Person in den 10 Minuten knacken. Und selbst wenn du mit 10 Personen angreifst was wohl so gut wie nie passieren wird, können maximal 3, allerhöchstens 4 Leute Dietrich mitnehmen, damit die reinkommen, da kannst du ja maximal 8 Kisten knacken...

**Comment by Timkoe** [comment]
Absolut richtig.
Je mehr Dietriche du mitnimmst desto mehr kannst du looten.
Wieso solltest du mehr als 2 doppelkisten aufrbechen dein Inv ist eh nicht groß genug.
So können Gilden bei Raids maximal 30-50% des Loots verlieren.
Außerdem ist in jeder Kiste etwas wertvolles wenn du lediglich 30 verschließen kannst
