### ISSUE TITLE
Balancing: Sprengladung Cooldown 90/90 sekunden ab jetzt

### ISSUE THREAD

**Issue by Timkoe** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#471]

**Comment by Timkoe** [comment]
done

**Comment by TimK1998** [comment]
Ist erst jetzt done, weil Regenrationszeit hardcoded ist. Allerdings: Soll Obsibrecher auch 90 Sekunden haben oder nicht?

**Comment by Timkoe** [comment]
Jo das stimmt, Obsi Brecher sollte dann am besten auch 90/90 haben. Oder man macht den Obsibrecher etwas schwieriger und macht 90/60 draus.

Aber denke fürs erste ist es am besten es einheitlich 90/90 zu machen.


Die Regenerationszeit war doch schon 90?

**Comment by Timkoe** [comment]
Hab den CD von Obsibrecher auf 90 geändert in der config
