### ISSUE TITLE
Task: Dietrich: Anzahl knackbarer Kisten abhängig von Gesamtzahl verschließbarer Kisten machen.

### ISSUE THREAD

**Issue by Timkoe** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#473]
**Neue Regelung:** Jede Gilde kann kann bis zu 30 Kisten verschließen.
Davon können exakt 40% bei einem Gildenangriff aufgebrochen werden.
(40% immer von den tatsächlich verschlossenen Kisten also wenn nur 10 verschlossen dann 40% davon)

-----------------------------------------------------------

Mitgliederzahl | Nr von verschließbaren Kisten
-- | --
0-3 | 9
4-6 | 18
7-8 | 24
9-10 | 30

Nr von knackbaren Kisten bei Max Anzahl:
Bei 9 -> 4 
Bei 18 -> 7
Bei 24 -> 10
Bei 30 -> 13

**Comment by Timkoe** [comment]
Ändere entsprechend den Dietrich CD dann wieder auf 90

**Comment by TimK1998** [comment]
Siehe #469

**Comment by Torre1234** [comment]
Wir können das System gerne heute nochmal besprechen, da einige Änderungen denke ich etwas überhastet und noch nicht ausgereift waren.
Wir haben bei bspw. den CD changes aber durchaus durchgerechnet, unsere Sorge war dabei, dass man rechnerisch die 30 Truhen bei moderatem Dietrich CD legit alle knacken kann.
Und alle anderen Truhen sind sowieso offen, d.h. man kann einer Gilde in 1 gutem Angriff legit alles wegnehmen. 
Sicherlich kann man bei einer starken Verteidiger base nur schwer mit 10 Mann die Dietrich nutzen rein, aber bei 90s CD kann 1 Spieler mit Dietrich 6 Kisten knacken. Heißt 5 Dietriche und man hat alle 30 Truhen, und das ist durchaus möglich, vor allem bei schwachen Gilden mit wenig/keiner Alo Erfahrung kommt man mit 15 Belagerungsskills locker in den Bunker und nimmt Ihnen dann litterally alles was irgendwie Wert hat, bis auf ihre 1 Reihe der Enderchest(vorausgesetzt sie tragen auch immer alles von Wert in diese, was da sie nur am spawn ist auch nicht immer der Fall sein wird). 

Ein Limit an knackbaren Truhen ist da deutlich besser, wobei wir uns halt nicht sicher waren wie gut das umsetztbar ist. Aber wenn wir ein Limit von 1/2 oder auch 2/3 setzen, ist die Frage, wie sehr das mitnehmen mehrerer Dietriche belohnt wird. 
Die Dynamik, dass Angreifer quasi Risiko gehen und versuchen können mit weniger Belagerungsskills einen Raid zu gewinnen, um dann mit mehr Loot wegen Dietrich belohnt zu werden, empfanden wir dabei als durchaus sinnvoll.
Dass die genauen Werte an Verschließbaren, und damit auch Knackbaren Truhen von der Mitgliederanzahl abhängt, können wir nochmal überdenken. Kleine Gilden haben denke ich genug Nachteile, jeder Gilde Flat 30 verschließbare Truhen und 15-20 davon Knackbar machen wäre da denke ich durchaus ne gute Alternative, aber lass uns da doch einfach heute nochmal zusammen setzten und eine finale Version diskutieren.

**Comment by TimK1998** [comment]
Jo alles klar

**Comment by Timkoe** [comment]
Wir haben exakt das gemacht.
Der Dietrich CD sind keine 240 sondern 90 Sekunden.
Mit dem Cap kannst du exakt 40% der Kisten einer Gilde öffenen ganz egal wie groß sie ist. 
Durch den CD kannst du das meistens sogar mit einer kleinen Gruppe Aaaaangreifern die vllt nur 2-3 Dietriche dabei haben bewerkstelligen. 
Gilden können pro Mitglied ca 3 Kisten verschließen. Dennoch können bei Gilden mit nur 9 verschlossenen Kisten auch nur 4 geöffnet werden. So kann niemand ausgenommen werden egal ob klein oder groß. 

Inwiefern soll das nicht durchdacht sein?

**Comment by TimK1998** [comment]
Ist jetzt so umgesetzt wie besprochen. Max 30. Davon 40% knackbar.

**Comment by Timkoe** [comment]
Das 40% Cap greift noch nicht 100%
bei nur 3 verschlossenen Kisten können 2 Kisten geöffnet werden.

**Comment by Timkoe** [comment]
Bei 39 Kisten funktionierts perfekt und 12 werden geöffnet.
Ist halt die Frage ob wir das bei den 2 von 3 ändern wollen ^^

**Comment by TimK1998** [comment]
Muss halt so sein, 3*0.4=1.2 und danach rundet der halt konsequent auf. Sonst wäre z.B. eine Kiste gar nicht zu knacken. Außerdem geht nur alles oder nichts, ich kann dem also nur sagen runde auf oder ab, aber nicht bei x Kisten machs so, manchmal aber auch anders...

**Comment by Timkoe** [comment]
alles klar
