### ISSUE TITLE
MessageChannel tab completer geht nicht

### ISSUE THREAD

**Issue by TimK1998** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#474]
@Kyraja Der Tab Completer callt zwar deine getMessageChannelMatchcodeJoinable(Language language, String channelName, boolean joinable) Methode, aber die funktioniert nicht. Er listet trozzdem alle Channel auf, egal ob die joinable sind oder nicht.

**Comment by Kyraja** [comment]
@TimK1998 keine Ahnung... der führt den Tabcompleter garnicht aus für die MessageChannels.... ich hab jetzt eine Stunde gesucht... vllt fällt mir noch was ein
