### ISSUE TITLE
Artefakt-Gilden: Spieler verlieren Gilde nach relogg nachdem das Artefakt im Gildenblock platziert wurde und der erste Artedrop abgeholt wurde..

### ISSUE THREAD

**Issue by Timkoe** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#479]
Found
Spieler verlieren ihre Gilde wenn das Artefakt im Gildenblock platziert wurde und sie reloggt haben.
Der Gildenleader wird bei g info noch als Leader gelistet taucht aber nicht mehr in der Gildenmitgliederliste auf und die Gilde zählt als Offline

Steps
- Kristalle zerstören mit 2 verschiedenen Gilden (Beide in Schutzzeit)
- Den Artefaktblock abbauen
- Den Artefaktblock als Artefaktträger im Gildenblock platzieren
- Mit Rechtsklick am Gildenblock auf das ArtefaktIcon klicken um die ersten Drops zu erhalten
- Aussloggen und ca 5 Minuten warten (Solange der Spieler ausgeloggt ist erscheint er bei g info noch als Mitglied der Gilde)
- Einloggen -> Sobald der Spieler eingeloggt ist, ist er nicht mehr in der Gilde und wird bei G info nicht mehr aufgelistet.

Außerdem:
Können die Artefaktdrops die eine fremde Gilde früher nicht abgeholt hat im eigenen Gildenblock geclaimt werden

Screenshot:
https://media.discordapp.net/attachments/701183386500333710/708760302950547456/2020-05-09_20.50.48.png?width=1230&height=677

**Comment by TimK1998** [comment]
Okay @Kyraja , ich glaube ich weiß warum die Gilden nicht richtig gespeichert wurden. Also erstmal, der Grund, warum wenn man reloggt nicht mehr in der Gilde "Schlepphoden" war, ist, dass diese Gilde nie in der DB existiert hat. Daher gab es auch sekündlich einen Fehler, das die nicht existierende Gilde nicht im User gespeichert werden konnte:

Cannot add or update a child row: a foreign key constraint fails (`lostkingdoms`.`user`, CONSTRAINT `FK6u27d0v20jxlp4of1v0s6xsw0` FOREIGN KEY (`guild_guild_id`) REFERENCES `guild` (`guild_id`))

Damit ist direkt die Frage geklärt warum die Gilde im User Element nicht gespeichert werden konnte. Jetzt zur nächsten Frage: Warum wurde die Gilde nicht beim create gespeichert. Auch hierauf gibt es eine Erklärung. Beim create kam ein Fehler, dass es für die Id. Nr. 4, die der Gilde Schlepphoden zugewiesen wurde, schon eine Gilde mit dieser Id in der DB gibt: 

Duplicate entry '4' for key 'UK_erd2aiyklqfojmvbc645v0qd2'

Also habe ich mal in die DB geschaut und es gibt tatsächlich schon eine Gilde mit dieser ID. Jetzt kommen wir also zu großen Preisfrage: Warum zum Fick hat Hibernate dem neuen Objekt eine ID zugewiesen, die es schon gibt????

An der Stelle kann ich jetzt echt nur raten und ich denke auch nicht, dass das der Grund ist. Eine der 4 Gilden in der DB ist disbanded, wird also bei Serverstart nicht geladen:

getAllGuilds() - [de.lostkingdoms.core.guild.Guild@4e5d25a9, de.lostkingdoms.core.guild.Guild@64358f0f, de.lostkingdoms.core.guild.Guild@421a6587]

Jetzt die Frage an dich @Kyraja. Vergibt der die Ids nach der Anzahl an geladenen Gilden, also nach dem Motto 3 gibts, dann geb ich dem doch mal die ID 4? Oder wie funktiuoniert das? Weil ansonsten muss es einen anderen Grund dafür geben, warum Hibernate so dumm ist. Jedenfalls ist das kein Fehler, den man auf die leichte Schulter nehmen kann.

**Comment by TimK1998** [comment]
Okay, also ich hab mir jetzt selbst nochmal ne Gilde erstellt und der hat er witzigerweise die ID 7 vergeben, also 3 Ids übersprungen... Aber immerhin gespeichert ohne Fehler

**Comment by TimK1998** [comment]
Hm also eigentlich sollte der mit long id = (long) session.save(transactionClass); dem automatisch ne richtige ID zuweisen, also ich hab wirklich keine Ahnung warum er da eine exisitierende vergeben hat. Echt komisch.

**Comment by TimK1998** [comment]
Hab jetzt mal gegoogelt und viele sagen, dass sowas passieren kann, wenn der Generater scheiße ist. Wir benutzen jetzt

@GenericGenerator(name = "native", strategy = "native")
@GeneratedValue(generator = "native")

Keine Ahnung was genau das aussagt. Vielleicht gibts da ja was besseres.

**Comment by Timkoe** [comment]
Dieser Bug ist wahrscheinlich der gleiche von #482
https://github.com/Lost-Kingdoms/Lost-Kingdoms-IssueTracker/issues/482

**Comment by Timkoe** [comment]
Siehe #482

**Comment by Timkoe** [comment]
das restesten wir auch nochmal

**Comment by Timkoe** [comment]
Ist fixed
