### ISSUE TITLE
Bei Tempban: Steht nur Connection Lost für gebannten und im Chat ist keine Nachricht sichtbar

### ISSUE THREAD

**Issue by Timkoe** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#480]
Found
Bei Tempban: Steht nur Connection Lost für gebannten und im Chat ist keine Nachricht sichtbar
Ebenfalls ist autocomplete für Spielernamen nicht möglich.

Bei Kick: Ist nachricht im Chat sichtbar aber der gekickte Spieler sieht nicht weshalb er gekickt wurde

**Comment by TimK1998** [comment]
1. Wie stellst dir denn ein Tab Complete vor, wenn der Spieler nicht online ist? Willst du immer Warten bevor der wieder online kommt, bevordu ihn bannst?
2. Chat Nachricht ist definitiv sichtbar, wenn man den Befehl richtig verwendet -> Wiki 
3. Kann ich nichts daran ändern ist ein Bug von Spigot

**Comment by Timkoe** [comment]
1. Tab Complete wenn der Spieler on ist natürlich wie bei jedem anderen command auch
2, Der Spieler wird wie beschrieben mit /admin tempban Name zeit grund  
gekickt keine Nachricht wird gezeigt und er kann reconnecten.

**Comment by TimK1998** [comment]
1. Wenn ich das einstelle akzeptiert der aber nur Namen von Spielern die online sind
2. Wenn mans richtig mach gehts. Zeit nicht 1 oder 5 oder was auch immer sondern 1d für Tage 1m für Minuten, ....
