### ISSUE TITLE
Gildenkampf Winmessage ist falsch

### ISSUE THREAD

**Issue by Timkoe** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#481]
![grafik](https://user-images.githubusercontent.com/55351056/81485323-7ff2a680-924c-11ea-9c38-402eb93e11ec.png)

Farben inkorrekt.
Wäre nice wenn da noch steht die Gilde XYZ hat den Gildenkampf gegen XYZ gewonnen!

**Comment by oroshikirin11** [comment]
WIRD GEMACHT
