### ISSUE TITLE
Belagerungsskills können auf Gildengebiet geslottet werden

### ISSUE THREAD

**Issue by Timkoe** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#483]
Belergerungsskills können im Gfight auf Gildengebiet geslottet und verwendet werden.
(auch ohne op)
Normale Skills können allerdings nur am Spawn geslottet werden

**Comment by Timkoe** [comment]
Issue noch reproduzierbar auf eigenem Gildengebiet.
(Dev Test Server)

**Comment by TimK1998** [comment]
@Kyraja Was auch immer du da für Änderungen gemacht hast, die Lösen das Problem nicht. Der BSlots Command listet nur deine Slots auf, der sollte natürlich überall funktionieren. Musst den Code in den BSlot Command packen.
