### ISSUE TITLE
Spawn im Nether / Verhindern dass Spieler Portale in den Spawn generieren

### ISSUE THREAD

**Issue by Timkoe** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#487]
Wir müssen irgendwie verhindern dass Spieler Netherportale in den Spawn generieren
Können wir das entsprechende Spawngebiet im Nether Claimen oder so?

**Comment by Timkoe** [comment]
was ist jetzt die lösung dafür? @Kyraja

**Comment by Kyraja** [comment]
Portals können auf nicht Nether & Default nicht angezündet werden. Außerdem generiert er keine Portals auf anderer Seite, wenn dort keine Default Welt ist
