### ISSUE TITLE
[Class-System]Vorschlag Eisfesseln

### ISSUE THREAD

**Issue by AioAioAio** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#488]
Hexer Eisfesseln Reichweite 6->10 

einfach weil 6 blöcke schon fast in meele range ist und man besser kiten/chasen kann wenn es etwas mehr reichweite hat

**Comment by Timkoe** [comment]
Ändere es nachher

**Comment by Timkoe** [comment]
Folgende Änderung:
Hexer Eisfesseln Reichweite 6->10
Eisfesseln Dmg -> 160

Entity System:
Feuer DMG von 0.025 auf 0.035 erhöhen

Feuerschuss
1 feuertick mehr

**Comment by Timkoe** [comment]
Fixed
