### ISSUE TITLE
Schleichen & Feuerschuss sind hardcoded

### ISSUE THREAD

**Issue by Timkoe** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#491]

**Comment by TimK1998** [comment]
![Unbenannt](https://user-images.githubusercontent.com/7693029/81600208-89554d80-93c9-11ea-8f3f-bb9e090ea9e6.PNG)

Kann ich nicht bestätigen. Funktioniert super mit /skill sneak, /skill blazing_missiles
