### ISSUE TITLE
Spieler können sich während der Lootingphase eines Gildenangriffs zum g home teleportieren

### ISSUE THREAD

**Issue by Timkoe** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#494]
Das sollte während der Lootingphase nicht möglich sein.

**Comment by Kyraja** [comment]
@Timkoe Hab eingebaut das du dich generell nicht von feindlichen Gilden porten kannst

**Comment by TimK1998** [comment]
@Kyraja Das ist damit glaube ich nicht gemeint. Es ist gemeint, dass die verteidigende Gilde sich während der Lottingphase zu ihrem eigenen g home tpen kann. Glaube ich zumindest.

**Comment by Timkoe** [comment]
Genau :)

**Comment by Timkoe** [comment]
passt
