### ISSUE TITLE
Gildenränge nach restart nicht übernommen

### ISSUE THREAD

**Issue by Tysaby** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#496]
Gildenränge werden nach einem serverrestart wirder zurückgesetzt (adel offizier )
nach einem relog bleiben sie erhalten

**Comment by TimK1998** [comment]
Das selbe wie #497

**Comment by Timkoe** [comment]
Dann bitte retesten wenn #497 gefixt ist.
