### ISSUE TITLE
GIlde nach relog gewechselt

### ISSUE THREAD

**Issue by Tysaby** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#497]
nach relog als gildenleiter der gilde Tets (tst) als mitglied der gilde BLABLA geendet
daraufhin konnte ich die gilde nicht mehr verlassen und war in beiden zur selben zeit drinnen

**Comment by TimK1998** [comment]
Das hat jua gut funktioniert @Kyraja ^^ Ich knn evtl auch mal die DB zurücksetzen, vielleicht ist einfach nur die verbuggt...
