### ISSUE TITLE
Guild create tag allready exists meldung

### ISSUE THREAD

**Issue by Tysaby** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#498]
erstellt man eine gilde mit einem bereits vorhandenen tag kommt in chat die fehlermeldung:create.error.tag.exists    anstelle von der meldung wie zum beispiel beim gildennamen das dieser bereits existiert

**Comment by Timkoe** [comment]
Ich fügs den messages hinzu

**Comment by oroshikirin11** [comment]
Sollte gefixt sein, sofern die Message hier richtig geschrieben wurde.

**Comment by Tysaby** [comment]
gefixt
