### ISSUE TITLE
Möglichkeit mehr als 1 gildenblock zu erhalten

### ISSUE THREAD

**Issue by Tysaby** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#499]
Erstellt man gilde 1 , kauft einen gblock und  löst diese wieder auf , macht eine neue und kauft einen neuen gblock hat man nun einen gilde und 2 gildenblöcke im inventar. Der erstplatzierte block funktioniert normal der zweiteplatzierte garnicht , jedoch lässt dieser sich in die region des gildenblocks setzen in die eigentlich keine blöcke platziert werden können sollten

**Comment by TimK1998** [comment]
? GM?
