### ISSUE TITLE
gilden rename funktioniert nicht richtig

### ISSUE THREAD

**Issue by Tysaby** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#501]
gildenblock rename funktion funktioniert nicht richtig. Wählt man die funktion im gildeblock aus wird man aufgefordert den neuen namen in den chat einzugeben. (beispielsweise TestGilde) daraufhin kommt die Fehlermeldung : der Befehl /g renameTestGilde existiert nicht (und ja ich habe das /g nicht selber eingegeben sondern nur den aufgeforderten namen (leertaste fehlt? )) 
versucht man die gilde per befehl umzubenennen ( /g rename TestGilde) heißt es das man diesen Befehl nur im gildenhaus benutzen kann was wenig sinn macht wenn der befehl eigentlich durch den gildenblock genutzt werden sollte
weiterer Verbesserungsvorschlag : Beim umbennen einer gilde kann man sowohl den namen als auch den tag ändern

**Comment by Kyraja** [comment]
@Tysaby Problem wird gefixt. Für Änderungen bitte neuen Task machen. Danke

**Comment by TimK1998** [comment]
Habs schon @Kyraja
