### ISSUE TITLE
Gildenblock umsetzen obsi bleibt stehen

### ISSUE THREAD

**Issue by Tysaby** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#502]
setzt man einen gildenblock um bleibt das obsidian unter diesem stehen. einfachste lösung gildenblock umsetzen auf 1000 gold kosten setzen

**Comment by Kyraja** [comment]
@Tysaby Yes. Nur der Gildenblock wird entfernt. Ändere ich das auch die Platform geht
