### ISSUE TITLE
Task: Neues TP update als default Pack einfügen

### ISSUE THREAD

**Issue by Timkoe** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#504]

**Comment by TimK1998** [comment]
Wasn das hier eigentlich?

**Comment by Timkoe** [comment]
Wambo hat Schlössertexturen ins Texturepack eingefügt, müssen die neue Version mal hochladen und reinmachen

**Comment by TimK1998** [comment]
Wie schlößertexturen? Dann müsste man ja die Diamanttextur überschreiben

**Comment by Timkoe** [comment]
der hat das so eingestellt dass das nur die textur hat, wenn das schloss zb. Privatschloss heißt

**Comment by TimK1998** [comment]
Sowas gibts mittlerweile? Krass. Dann muss er es aber definitiv so einstellen, dass des TP nicht checkt, ob das "Diamantschloss" heißt, weil das nämlich "§bPrivatschloss" heißt. Selbiges fürs Gildenschloss. Vielleicht hat ers ja aber auch schonmal ausprobiert und es funktioniert schon so

**Comment by Timkoe** [comment]
hat er

**Comment by TimK1998** [comment]
Dann müsstest dus mal neu hochladen und den Link hier reinschicken
