### ISSUE TITLE
Spielernamen bei Guildblock Lebensanzeige

### ISSUE THREAD

**Issue by Timkoe** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#507]
![grafik](https://user-images.githubusercontent.com/55351056/81725837-bb78b500-9486-11ea-961f-038b3f0b3284.png)

**Comment by AioAioAio** [comment]
![fdcb31af1e5ab21ea8fb7f37b1ada5f4-png](https://user-images.githubusercontent.com/60797363/81727181-d8ae8300-9488-11ea-9745-0fffb6745913.jpg)

**Comment by AioAioAio** [comment]
![8f441bbb01a53b1bc052513947faf1d8](https://user-images.githubusercontent.com/60797363/81728570-f67ce780-948a-11ea-991c-31b7acaff44f.png)

**Comment by AioAioAio** [comment]
![ef95a741478d6d43f23d23fcf7188804](https://user-images.githubusercontent.com/60797363/81730215-773ce300-948d-11ea-865a-2470326d4eeb.png)

**Comment by Timkoe** [comment]
Tippe mal das Problem besteht bei alles Gilden messages, seitdem der Playername im Gildenchat angezeigt wird.

**Comment by Kyraja** [comment]
Bitte nochmal neu testen, hab grad gepusht danke

**Comment by Timkoe** [comment]
fix confirmed
