### ISSUE TITLE
Passive Kriegerklärung

### ISSUE THREAD

**Issue by AioAioAio** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#513]
Wenn der Spieler 3 mal im Grenzgebiet getötet wird, wird kein Kriegerklärt
aber wenn er im Coregebiet getötet wird klappt es

**Comment by Timkoe** [comment]
ab 3 Kills im

**Comment by Timkoe** [comment]
bitte retesten

**Comment by Timkoe** [comment]
Im noncore-Gebiet wird der Gildenkampf leider immernoch nicht getriggert

**Comment by Timkoe** [comment]
pls retesten

**Comment by Tysaby** [comment]
funktioniert
