### ISSUE TITLE
Gildenwinnachricht hat noch falsche Farbe bei Gilde 2

### ISSUE THREAD

**Issue by Timkoe** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#514]
https://gyazo.com/5864b8be407ef9d1e1c67b85761d3105

**Comment by oroshikirin11** [comment]
Sollte eigentlich klappen, habe ich mir ja schonmal angeschaut.
Steht so in der DE Datei drinnen:
"guild.siege.block.destroyed":"Die Gilde§6 {0}§f hat die Verteidigung gegen§6 {1}§f verloren!",

**Comment by Timkoe** [comment]
Also gehts noch nich? @oroshikirin11

**Comment by oroshikirin11** [comment]
nö

**Comment by Tysaby** [comment]
außerdem ist die allgemeine nachricht vom server aus gesendet statt von der gilde
![serrrrrrver](https://user-images.githubusercontent.com/52243413/81984789-9fffdc80-9635-11ea-82b7-c6346b1696ad.PNG)

**Comment by TimK1998** [comment]
Das mit dem Server war glaube ich so gewollt, weil alle globalen Nachrichten über diesen Channel gebroadcastet werden, aber kann man natürlich auch ändern. Das mit der Farbe kann daran liegen, dass wenn man eine bereits existierende MEssage ändert, man die DB resetten muss, damit die Änderungen wirksam werden.

**Comment by Timkoe** [comment]
Die Servernachricht sollte so sein das stimmt

**Comment by TimK1998** [comment]
Dann liegt der Rest an der DB
