### ISSUE TITLE
Der Serverrang Headadmin kann nicht zugewiesen werden

### ISSUE THREAD

**Issue by Timkoe** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#515]
alle anderen Teamränge gehen.
/admin setrank Headadmin/HEADADMIN oder
/admin setrank Headadministrator
können nicht zugewisen werden

**Comment by TimK1998** [comment]
An der Stelle wäre es ganz gut @Kyraja, wenn man das so umsetzen würde wie beim Klassen Tab Completer. Weil aktuell completet der beim RankType die Enums, akzeptiert aber nur die eingaben in der richtigen Sprache, was n bisschen Quatsch ist.

**Comment by Timkoe** [comment]
bitte retesten

**Comment by Timkoe** [comment]
Fix verified
