### ISSUE TITLE
Combatlog: Bei serverrestart gespawnte Villager sind unsterblich nach Serverrestart

### ISSUE THREAD

**Issue by Timkoe** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#516]
Steps
- Spieler loggt sich kurz vor restart in wildnis aus
- Villager spawnt
- Server startet neu
- Villager steht da und kann nicht getötet werden

**Comment by Timkoe** [comment]
pls testen

**Comment by Tysaby** [comment]
gefixt
