### ISSUE TITLE
[Command]  /r Command

### ISSUE THREAD

**Issue by oroshikirin11** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#517]
/r Command zeigt immer an dass der User offline ist.
Irgend einer von euch hat da was direkt/indirekt geändert.

**Comment by Timkoe** [comment]
pls testen

**Comment by Tysaby** [comment]
immernoch nicht gefixt

**Comment by Kyraja** [comment]
@Tysaby Bei meinem Test hat er funktioniert. Da ging /r einwandfrei... kannste mir mal ein Bild machen? Vorher waren die Nachrichten falsch herum, dass hatte ich mit dem letzten close gefixt.

**Comment by Timkoe** [comment]
![grafik](https://user-images.githubusercontent.com/55351056/82076303-f1fc3d00-96dd-11ea-94ff-ade4ea8de285.png)

**Comment by Kyraja** [comment]
msg command wurde disabled... da er von MC kommt und wir da wenig machen können
