### ISSUE TITLE
serverrestart während des gildenkampfs

### ISSUE THREAD

**Issue by Tysaby** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#521]
restartet der server während eines g kampfs  endet dieser ohne sieg und ohne schutzzeit und kann nach serverrestart einfach neu begonnen werden. Problem ist also g fight beginnt man sprengt 30 minuten server restartet und hat wieder neue 45 minuten

**Comment by Timkoe** [comment]
Der Fight sollte entweder mit gleicher Zeit weitergehen oder es sollte 2h Schutzzeit (Wie nach gewonnenem Raid) geben.

**Comment by Kyraja** [comment]
@Timkoe ich muss mal schauen... das ganze in die DB zu bringen und zu starten ist nicht sooo trivial... da bin ich nen halbe tag mit beschäftigt das umzubauen.
Wäre da erstmal für die 2h variante

**Comment by Timkoe** [comment]
Okay die passt auch

**Comment by Timkoe** [comment]
retest pls

**Comment by Timkoe** [comment]
gilde kriegt noch keine schutzzeit nach restart würde ich aber so lassen. Hat jetzt nicht so die Prio
