### ISSUE TITLE
Vorschlag Bärenfalle

### ISSUE THREAD

**Issue by AioAioAio** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#522]
Bärenfalle
von 3 Stacks -> auf 2 Stacks ------ Nein
von 150dmg -> auf 300 ---------- Nein
slowness von 1-> auf 2 ------------ Nein
add effekte blindness 1 für 3sec ------ Nein
                   glowing für 5sec -------- ja

**Comment by AioAioAio** [comment]
Die jetztige Bärenfalle hat meiner Meinung nach keinen wirklichen Reward dafür das sie 
sichtbar aufm Boden liegt 150dmg mit Slowness ist kein wirkliches Reward.
Dafür das sie sehr einfach umgehbar ist, ist sie viel zu schwach

**Comment by Timkoe** [comment]
Änderung:
Glowing 5s

**Comment by TimK1998** [comment]
Game Designer: Mimimi 1 Bärenfalle mit 500 Dmg ist kein Reward.. wie wäre es denn mit 3 mit 150 DMG? 

Developer: *Ändert Bärenfalle aufwendig*

Game Designer: Mimimi 3 Bärenfallen mit 150 Dmg sind kein Reward.. wie wäre es denn mit 2 Bärenfallen mit 300 DMG

... to be continued :D

**Comment by Timkoe** [comment]
:D Ich hatte nie irgendein Problem mit der Falle ... not my fault

Du musst da nichts ändern, das mit dem glowing krieg ich glaub ich hin ansonsten wird nichts dran verändert

**Comment by TimK1998** [comment]
Ich weiß :D

**Comment by TimK1998** [comment]
Also Schaden könnte man meiner Meinung nach bestimmt auch auf 200 buffen, ohne dasss es zu krass ist.

**Comment by Timkoe** [comment]
Hab Glowing umgesetzt bitte testen

**Comment by AioAioAio** [comment]
glowing funktioniert

**Comment by Timkoe** [comment]
noice
