### ISSUE TITLE
Berufe changes 

### ISSUE THREAD

**Issue by Timkoe** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#523]
Dropchance beim Angeln verdoppeln von 2.5 & 0.075
auf 5 & 0.15
-> Aktuell zu schwach, haben Torre und seine Leute ganz gut vorgerechnet

- Lapisblocks statt Redstoneblocks als Drops bei allen Berufen
-> Nützlicher fürs Enchantsystem

-- bitte nochmal vorab zsm besprechen ---.

**Comment by Timkoe** [comment]
Im Doc & Wiki angepasst

**Comment by TimK1998** [comment]
Musst halt bedenken, dass das einer Verdopplung entspricht, was ich an sich nicht so schlimm finde, aber es gibt ja auch noch Chancen 2 oder 3 Items zu angeln, ich denke, dass ist in den Gedankengang nicht eingegangen, weil das dann rechnerisch einer VErdreifachung der Dropps entspricht.

**Comment by Timkoe** [comment]
Wie hoch sind denn die Chancen davon? Können wir dem vielleicht entgegenwirken indem wir diese Chancen wiederrum senken?

**Comment by TimK1998** [comment]
Naja aktuell siehts so aus:

1. 2.5+ 0.075
2. 1.25 + 0.0375
3. 0.625 + 0.0185

Also immer halbiert. Verdoppelst du also wie Wsk überall, erhöhst du die Dropps um mehr als das Dreifache.

**Comment by Timkoe** [comment]
Was sind denn 2 und3? ^^
Würde nur beim Angeln die Base wsk und den Increase erzhöhen sodass man insgesamt auf 20% kommt auf 100 statt 10

**Comment by TimK1998** [comment]
Ja 1. ist die Wsk für ein Item, 2. Für ein zweites, 3. für ein Drittes. Wobei ich merk gerade, dasss die falsch verschachtelt sind. Ich änder das einfach so, dass es am Ende passt mit den 20% auf 100

**Comment by Timkoe** [comment]
Okay perfekt thx

**Comment by Timkoe** [comment]
Testen Pls

**Comment by Timkoe** [comment]
passt
