### ISSUE TITLE
Improvement: /ch team bzw. Ingame Chat-Channel für Teammitglieder

### ISSUE THREAD

**Issue by Vollgasidiot** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#527]

**Comment by AioAioAio** [comment]
![894d64bbb40dc329dcce21f207f4ce76](https://user-images.githubusercontent.com/60797363/82127530-95b81c80-97b4-11ea-8ad7-671af1c06773.png)

Wasn das

**Comment by Timkoe** [comment]
Pls testen

**Comment by Timkoe** [comment]
Spielernamen werden noch nicht im Teamchat angezeigt.
![grafik](https://user-images.githubusercontent.com/55351056/82159047-fbc3a300-988b-11ea-862d-287653ed1ece.png)

Genauer konnte ich es nicht testen, da mal wieder kein weiterer Tester da war.

**Comment by Timkoe** [comment]
@Kyraja Bitte noch so ändern dass es durch blockmessages geblockt wird oder 
Nicht passiv angezeigt wird.
(Wegen streamenden Teammembern)

**Comment by Kyraja** [comment]
@Timkoe Was von beidem hätten sie denn gerne? Ich find das mit "passiv" schwierig, da so die member aktiv reingehen müssen um etwas mitzubekommen

**Comment by Timkoe** [comment]
Okay das stimmt. Machen wirs dann einfach in Blckmessages rein?
