### ISSUE TITLE
Improvement: /ch gilde zu /ch guild abändern, um konsistent mit anderen Befehlen zu bleiben

### ISSUE THREAD

**Issue by Timkoe** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#529]

**Comment by Kyraja** [comment]
@Timkoe Das geht nicht, das die Channel sprachenabhängig sind.

**Comment by Timkoe** [comment]
alle Befehle sind auf englisch, mir geht es nur darum dass der nicht aus der Reihe tanzt, muss jetzt aber nicht cor Release gefixt werden :)
