### ISSUE TITLE
gold banner funktionieren nicht

### ISSUE THREAD

**Issue by Tysaby** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#536]
weder das regionale noch das globale

**Comment by TimK1998** [comment]
Bitte testen, ob das Gold erhöht ist. Eine Chatnachricht wie bei Exp gibts nicht bei +x Gold

**Comment by Tysaby** [comment]
naja gut also das durchschnittsgold sah nicht so aus als würde es sich erhöhen wobei die spanne ja recht hoch ist. ich teste es nochmal kurz gegen
