### ISSUE TITLE
regionale ep boosts funktionieren nicht im nether und end

### ISSUE THREAD

**Issue by Tysaby** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#537]

**Comment by TimK1998** [comment]
Inwiefern? Lassen sie sich nicht platzieren, oder gibts nicht mehr exp oder wie?

**Comment by Tysaby** [comment]
Sie lassen sich platzieren aber es passiert nichts sonstiges
also weder die normale chatmeldung noch das sie mehr exp geben

**Comment by Timkoe** [comment]
würde sagen die sollte man nur in der Overworld platzieren können

**Comment by TimK1998** [comment]
Hab die jetzt einfach deaktiviert im Nether und End, WOBEI sie bei mir problemlos funktioniert haben in den anderen Welten

**Comment by TimK1998** [comment]
Warst du evtl. Level 100 Finn und hast deswegen keine MEssage bekommen?

**Comment by Timkoe** [comment]
@TimK1998 dh. man kann sie da einfach nicht mehr platzieren?
