### ISSUE TITLE
Exp banner range

### ISSUE THREAD

**Issue by Tysaby** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#538]
Laut shop sollen regionale banner 150 blöcke range haben , jedoch versucht man ein zweites neben ein schon existierendes banner zu stellen wird gesagt dies geht nicht in 50 blöcken reichweite zu anderen bannern derselben art
ist diese diffirenz sinnvoll und einfach leicht irreführend oder ein übertragungsfehler?

**Comment by TimK1998** [comment]
Ja ist schon gefixt jetzt
