### ISSUE TITLE
Spieler am Spawn können nicht mit Knöpfen und Türen interagieren

### ISSUE THREAD

**Issue by Timkoe** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#541]
(wenns gefixt wird bitte so machen dass die mit trapdoors nicht interagieren können)

**Comment by TimK1998** [comment]
Geht ausgezeichnet bei mir als Player ohne op. Da ist auch nichts im Plugin eingebaut was das verhindern würde

**Comment by Kyraja** [comment]
restesten

**Comment by Timkoe** [comment]
Das lag an der Spawnprotection von Vanilla wenn wir die Problemfrei abschalten können wärs nice
wenn nicht wäre es aber auch nciht so tragisch
