### ISSUE TITLE
[Command] g inspect 

### ISSUE THREAD

**Issue by oroshikirin11** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#572]
Der Server hat kurz mal alle Leute runtergeworfen als /g inspect benutzt wurde.
Diese Gilde hatte noch kein Gildengebiet.

**Comment by TimK1998** [comment]
Macht keinen Sinn Wenn du mir die Uhrzeit sagen könntest könnte ich da mal in die Konsole schauen
