### ISSUE TITLE
/skill schleichen im Chat unsichtbar machen

### ISSUE THREAD

**Issue by Vollgasidiot** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#576]
eigentlich wirklich nur logisch, denke ich

**Comment by Timkoe** [comment]
war auf alo auch nicht so sollte man halt rechtzeitig vorher casten
fänd ioch relativ unnötig

**Comment by Torre1234** [comment]
War auf alo safe so, nur friendly Spieler konnten den Command sehen, Gegner nicht. Es soll ja auch die Shift funktion ersetzen damit du dich nicht auf krampf übers feindliche Gebiet sneaken musst. Also ich wäre auch dafür
