### ISSUE TITLE
Beim tod verliert man das gold nicht richtig

### ISSUE THREAD

**Issue by Tysaby** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#577]
Spieler fällt in lava stirbt fast und teleport sich in sein home während er noch brennt. er verbennt im home im chat steht er verliert das gold hat es aber noch und es liegt nicht da. ( spieler hatte noch schutzzeit ) laut ihm reproduzierbar wobei sich das gold jedoch nicht duped

**Comment by Tysaby** [comment]
es scheint als ich nochmals ein wenig romgetestet hatte als würde nur die anzeige buggen

**Comment by Timkoe** [comment]
wenn nicht reproduzierbar einfach schließen @Kyraja
