### ISSUE TITLE
Immun dmg gegenüber

### ISSUE THREAD

**Issue by Tysaby** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#590]
manchmal , bisher nicht reproduzierbar , wird man immun gegenüber schaden und kann auch keinen mehr austeilen. (issue nur sicherheitshalber erstellt selbst wenn nicht reproduzierbar)

**Comment by Torre1234** [comment]
passiert gerade häufig

**Comment by Tysaby** [comment]
Jeder bisher gefragte der diesen bug hatte war vorher im nether

**Comment by stefanomazz** [comment]
Ja, liegt am Nether! Siehe post von Tim
