### ISSUE TITLE
Bergarbeiter: Ore-Farming

### ISSUE THREAD

**Issue by Torre1234** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#595]
Platzierte Ores sollen keine Exp geben(funktioniert erstmal auch), nach Restart werden diese jedoch nicht mehr erkannt und geben beim Abbauen Bergarbeiter Exp.

LOW PRIO, da Bergarbeiter-Level aktuell nur Haste verlängert, der Vollständigkeit halber aber dennoch interessant für die Zukunft.

**Comment by TimK1998** [comment]
Das ist leider unmöglich, kann nur durch Beobachtung bestraft werden. Aber ich kann nicht jeden gesetzten Ore Block in ner DB speichern und nach Restart neu laden.

@Timkoe Überlege dir da mal ne Strafe (Reset/Bann)

**Comment by Timkoe** [comment]
geöffnet nach wunsch von torre

**Comment by Kyraja** [comment]
@Timkoe @Torre1234 Und was ist da nun euer Vorschlag ? ^^ Also nur öffnen ist nicht drin 🗡️

**Comment by Timkoe** [comment]
Sehe da jetzt nicht so ein großes Problem ^^
Würde es auch nicht explizit in den regeln erwähnen
is Bugusing und das wird bestraft

**Comment by Torre1234** [comment]
Ups sry ist untergegangen, mb
bergarbeiter level abuse könnte man fixxen indem:
a)oreblöcke nicht mehr plaziert werden können(wie bei Diamant/eisenblöcken auf gildengebiet)
b)silk touch keine exp mehr für dias(fixxt nur dia abuse nicht bspw gold was 1/2 gibt, weniger gut)
