### ISSUE TITLE
/g fight loss geht nicht in Statistik ein

### ISSUE THREAD

**Issue by Vollgasidiot** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#599]

**Comment by minecabl** [comment]
Zur Doku:
Gildenkampf von Intervention (Angreifer) gegen Requium (Verteidiger), ausgelöst durch Passives Startsystem. 
Gildenblock wurde schon angehittet, allerdings wurden wir dann getötet und Kampf verloren. 
Nach Kampf wurde Stats und Elo beider Gilden nicht aktualisiert. 
Schutzzeit wurde vom Beginn des Gfights aus 4 Stunden korrekt an Requium gegeben.

**Comment by Timkoe** [comment]
passiert glaube nicht mehr
