### ISSUE TITLE
Im Nether respawnen keine Mobs sobald der chunk einmal geladen wurde

### ISSUE THREAD

**Issue by Kamuuh** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#605]
Es respawnt nichts wo man schon mal war 30 min+ in einer Festung verbracht ohne das Mobs respawnt sind

**Comment by Timkoe** [comment]
noch valid?

**Comment by LostKingdoms** [comment]
Konnte ich nicht bestätigen
