### ISSUE TITLE
Wutsprung & Hinterhalt funktionieren nicht auf Spieler

### ISSUE THREAD

**Issue by Timkoe** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#611]
17:31] BRO_GAMER1468: Hinterhalt geht nicht
[18:14] Maximiu234: Wutsprung funktioniert aktuell auch nicht, man springt nicht zum Gegner, andere Effekte kommen jedoch

**Comment by TimK1998** [comment]
Problem: Bei mir gehts

**Comment by Timkoe** [comment]
vllt nur auf mobs nicht

**Comment by VMMarco** [comment]
In der Arena geht es nich

**Comment by Kyraja** [comment]
@Timkoe Retesten
