### ISSUE TITLE
Jobs-Abilities werden bei Interaktion mit Kisten etc aktiviert

### ISSUE THREAD

**Issue by CubexsOne** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#612]
Sobald man etwas anklickt mit dem man interagieren kann ( Kisten, Craft-Table etc ) und man hat das dementsprechende Tool in der Hand aktiviert sich die Job-Fähigkeit.

Weiß jetzt nicht wie schlimm das ist, nur manchmal etwas nervig.

**Comment by oroshikirin11** [comment]
fixed
