### ISSUE TITLE
Wasser/Lava platzierbar im unzubaubarem Gblock bereich

### ISSUE THREAD

**Issue by Ricokoe** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#614]
Wasser/Lava platzierbar im unzubaubarem Gblock bereich

**Comment by Kyraja** [comment]
@Ricokoe Meinst du direkt neben dem Block oder lassen sie es in den Bereich reinlaufen ?

**Comment by Kyraja** [comment]
Fixed
