### ISSUE TITLE
Bibliothek erweitern

### ISSUE THREAD

**Issue by Torre1234** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#619]
Die Schilder, bei denen man 30 MC-Level für 50g in eine Flasche abfüllt bitte auch in der Bib aufhängen.
Zusätzlich Schilder, welche Knockback für 100g entfernen hinzufügen.

**Comment by VMMarco** [comment]
100g ist vielleicht etwas knapp das könnte man eigentlich auch auf 250g oder sogar noch höher setzen

**Comment by TimK1998** [comment]
jo

**Comment by oroshikirin11** [comment]
Sollte beim nächtsen update Done sein
