### ISSUE TITLE
Gildeschlösser blockieren neue mitglieder

### ISSUE THREAD

**Issue by Tysaby** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#625]
wird eine kiste mit einem gildeschloss verschlossen und danach kommt ein neues mitglied in die gilde ist die kiste für ihn trotzdem verschlossen. Neu abgeschlossene kisten gehen (aufgetreten bei corrupted/eropster)
konnte bisher leider nicht testen ob dies immer der fall ist

**Comment by Kyraja** [comment]
Auf UUID umstellen

**Comment by TimK1998** [comment]
Retest pls
