### ISSUE TITLE
[Spawn] Boote sind am Spawn placebar

### ISSUE THREAD

**Issue by oroshikirin11** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#626]
Boote sind am Spawn placebar, potential für trollaktionen

**Comment by TimK1998** [comment]
Lässt sich meines Wissens nicht tracken

**Comment by Kyraja** [comment]
@TimK1998 Ich glaube Interact Event mit getiteminhand aber muss man mal ausprobiern
