### ISSUE TITLE
[Vorschlag] /g info => Klassenlevel-Schnitt anzeigen

### ISSUE THREAD

**Issue by stefanomazz** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#629]
Am besten die höchste Klasse immer nehmen.

Nicht das in 2-3 Wochen wenn viele 100 sind, eine zweite Klasse Leveln und dann ist der Schnitt plötzlich unten.

**Comment by TimK1998** [comment]
Bitte vorher mit Tim absprechen ob das überhaupt sinnvoll ist

**Comment by Timkoe** [comment]
Finde es um erhlich zu sein unnötig das anzuzeigen
