### ISSUE TITLE
Man kann überall unslottten

### ISSUE THREAD

**Issue by Tysaby** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#631]
man kann seine slots überall löschen selbst wenn man nur neue setzen kann wenn man am spawn ist

**Comment by TimK1998** [comment]
Unter entities -> user -> menu -> impl -> slotMenu? -> Suchen wie Skills geunslottet werden und ab da den WEg nachvollziehen wo man die ABfrage inbauen muss. Ich glaube im Menu mache ich nichts anderes als den Spieler den /slot Befehl ausführen zu lassen

**Comment by Timkoe** [comment]
muss nicht gefixt werden
