### ISSUE TITLE
[NO PRIO] Axt Enchanten bekommt man 80% Knockback

### ISSUE THREAD

**Issue by badnumb3rs** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#634]
Man bekommt fast nur Knockback 2 Äxte bei LvL 30. Kann man da die Chance anpassen?

**Comment by TimK1998** [comment]
Sind 1:1 die gleichen wie bei Schwertern

**Comment by TimK1998** [comment]
Wie gesagt, ich checke nur, ob es Axt Schwert oder Sense ist und führe dann genau den selben Code aus. WEnns bei den anderen Items nicht auch so ist -> Close

**Comment by badnumb3rs** [comment]
Ich frage mal rum, melde es dann hier drunter

Holen Sie sich Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: Tim Küchler <notifications@github.com>
Gesendet: Wednesday, May 27, 2020 8:41:46 AM
An: Lost-Kingdoms/Lost-Kingdoms-IssueTracker <Lost-Kingdoms-IssueTracker@noreply.github.com>
Cc: badnumb3rs <maas-julian@outlook.de>; Author <author@noreply.github.com>
Betreff: Re: [Lost-Kingdoms/Lost-Kingdoms-IssueTracker] [NO PRIO] Axt Enchanten bekommt man 80% Knockback (#634)


Wie gesagt, ich checke nur, ob es Axt Schwert oder Sense ist und führe dann genau den selben Code aus. WEnns bei den anderen Items nicht auch so ist -> Close
