### ISSUE TITLE
Spieler die offline sind werden bei /g info als online angezeigt wodurch man keine protection hat

### ISSUE THREAD

**Issue by Kamuuh** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#639]
Wir waren zu 2. online in einer Gilde mit 8 Leuten. Weil jedoch Spieler die seit mind ner std offline sind als online registriert werden können andere Gilden ohne Wither und Poison effekt auf das Gebiet

**Comment by Kyraja** [comment]
"Player erscheinen doppelt in der /g info Liste ob diese auch doppelt gezählt werden (in bezug auf online Status) ist unklar.
Passiert nach einem AFK-Kick"

**Comment by Kamuuh** [comment]
Zudem wird XP geteilt wenn die Persond ie durch den AFK-Kick gekickt wurde in dem Bereich stant wo die Monster getötet werden

**Comment by Kyraja** [comment]
Fixed
