### ISSUE TITLE
Spieler können enderperlen am Spawn werfen (und skippen damit jumpnruns)

### ISSUE THREAD

**Issue by Timkoe** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#642]

**Comment by TimK1998** [comment]
Gibt nen EnderPearlThrowListener oder so ähnlich irgendwo, wo auch der CD getrackt wird. Da einfach ne Spawn abfrage einbauen. Aber bitte bedenken für Spawnabfrage:

if(region.getRegionType() == RegionType.SPAWN || region.getTregionType().getBaseRegion == RegionType.SPAWN) 

Zweiteres um auch die Subregions am Spawn mit drin zu haben
