### ISSUE TITLE
Improvement: Gildenschutz

### ISSUE THREAD

**Issue by Torre1234** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#644]
Gilden sind aktuell bereits ab 3 Spielern online, die Nachtprotection ist von 01:00 Uhr bis 11:00 Uhr.
Beides bietet dabei zu viel Spielraum für Abuse, nach 12 Uhr unter der Woche mit maximal 10 Spielern 3 Verteidiger angreifen ist komplett unverhältnismäßig. Ist so meines Wissens nach zum Glück noch nicht geschehen, sollten wir aber schon vorher verhindern, da das Geschrei(zurecht) groß wäre.

Besser: Gilden erst ab mindestens 4 Spielern als online werten, Nachtschutz bereits um 00:00 Uhr bis 11:00 Uhr wirken lassen. Alternativ müssten wir in der Zukunft bei Angriffen das Verhältnis von Angreifern zu Verteidigern regulieren/limitieren. Vorerst können diese 2 einfachen Werteveränderung jedoch schon eine fairere Umgebung mit weniger Abusepotential schaffen.

**Comment by Timkoe** [comment]
passt bitte im konzept noch anpassen @Torre1234

**Comment by Torre1234** [comment]
Veränderte Online-Werte sind live, neue Nachtschutz-Werte auch? @Kyraja 
Wenn ja /close und ich trags im doc und wiki ein

**Comment by Kyraja** [comment]
ja mit dem nächsten start, sollte auch die Uhrzeit berücksichtigt werden zwischne 0 und 11 Uhr
