### ISSUE TITLE
reloggen resettet cds % healed

### ISSUE THREAD

**Issue by Tysaby** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#646]
reloggt man ist man danach wieder fulllife und hat keine cds mehr inklusive z.b. pickaxe cd

**Comment by TimK1998** [comment]
Ja hatte ich so eingestellt, da dass sonst heftig rumgebuggt hatte mit dem Leben, ich schaus mir nochmal an heute

**Comment by Kyraja** [comment]
Müssen wir dringend anschauen.. die scheinen das gut zu nutzen...

https://streamable.com/s0wsxw

**Comment by TimK1998** [comment]
Ist das nicht ganz klar Bugusing?

**Comment by Torre1234** [comment]
ja, combatlog abuse halt
