### ISSUE TITLE
[Gilde] Nachtschutz funktioniert nicht

### ISSUE THREAD

**Issue by oroshikirin11** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#648]
Nachtschutz funktioniert nicht
In diesem Fall wurde ein Spieler auf dem Gildengebiet getötet.

**Comment by Kyraja** [comment]
Passiv hab ich vergesen^^

**Comment by Kyraja** [comment]
Eingebaut, sollte nächstes Patch kommen
