### ISSUE TITLE
[Hexer] Sense bekommt keinen Schaden bei Feuerschuss

### ISSUE THREAD

**Issue by oroshikirin11** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#649]
Sense bekommt keinen Schaden bei Feuerschuss
Im vgl. zu anderen Klassen unfair
Sense hält ewig

**Comment by Kyraja** [comment]
Ist das verhalten bei Hieb z.b. anders?

**Comment by TimK1998** [comment]
Erstens das was Flo fragt. Zweitens: ist die Umsetzung gewollt @Timkoe ?

**Comment by Timkoe** [comment]
Dafuq ne das ist nirgends so finde ich auch unnötig
