### ISSUE TITLE
[Chat / Obsisteuer] Betrag bei der Chatanzeige der Obsisteuer abschneiden

### ISSUE THREAD

**Issue by oroshikirin11** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#650]
Betrag bei der Chatanzeige der Obsisteuer nach der zweiten Nachkommstelle abschneiden
https://i.badlion.net/ukM2dwiyu5G4RwumT22kca.png

**Comment by TimK1998** [comment]
Utils.round
