### ISSUE TITLE
[Spawn] Subtypen von Booten sind noch placebar

### ISSUE THREAD

**Issue by oroshikirin11** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#651]
Subtypen von Booten sind noch placebar
Alle Sorten außer Eiche sind noch platzierbar, damit kann man sich z.B in die Arena buggen

**Comment by TimK1998** [comment]
Wenn dem so wäre bitte schauen wir normale Boote verhindert werden und abändern

**Comment by oroshikirin11** [comment]
Ich bin dran
