### ISSUE TITLE
Spieler hatte keine normale regeneration mehr und der Heal spell geht nicht. 

### ISSUE THREAD

**Issue by Kamuuh** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#658]
Bei damage wurde das leben auf full life gesetzt.  Man nimmt trotzdem schaden.

**Comment by Kyraja** [comment]
@Kamuuh weißt du noch den Spieler?

**Comment by Kamuuh** [comment]
> @Kamuuh weißt du noch den Spieler?

 Snorrree
