### ISSUE TITLE
[Sprengladung] Extended Sticky Pistons werden ab und zu bei Sprengung gedropt

### ISSUE THREAD

**Issue by oroshikirin11** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#666]
Extended Sticky Pistons werden ab und zu bei Sprengung gedropt und regenrieren dann nicht wieder.

Sonst regenrieren  extended Pistons in verbuggter Form zurück, dh: Die Extension die nicht gesprengt wurde ist noch da + der piston an sich ist im normal zustand generiert

**Comment by oroshikirin11** [comment]
Die Repeater hinter den Pistons werden auch gedropt.
Redstone Schaltung nach jedem Raid kaputt, richtig cancer

**Comment by TimK1998** [comment]
Ist bekannt kann man nicht fixen

**Comment by oroshikirin11** [comment]
Irgendwie muss man da doch was machen können, keiner hat Bock seine komplette Schaltung neu zu verkabeln / aufzureißen nach jedem Kampf.
Andere Server haben es ja auch irgendwie hinbekommen.
Redstone rauszuhauen ist auch völlig behindert weil es einem einfach sooo verdammt viel nimmt.

**Comment by Torre1234** [comment]
ja, kann so keien Lösung sein, die leute quitten Reihenweise den Server wenn ihre gebauten Sachen wegbuggen. Das ist die eine konstante, Level und Base kann dir keiner nehmen, nur Items. Eventuell bei /g fight chunk backup von gidlengebiet machen, und das nach dem fight auf den Server spielen? Wenn wirs bei Sprengladung nicht können brauchen wir nen Workaround

**Comment by stefanomazz** [comment]
Jo stimme Torre zu, wenn man das nicht gefixt kriegt, hauen Leute ab. Vielleicht extra Schutz für die ganzen Sachen die man nicht regenerieren kann, bzw. Redstone Stuff allgemein.

**Comment by VMMarco** [comment]
Wie wäre es denn wenn alle Blöcke die gesprengt werden gespeichert werden und nach dem g fight zurückgesetzt werden (erst normale blöcke dann redstone) ?

**Comment by TimK1998** [comment]
Darum gehts nicht, die Blöcke können einzeln nicht existieren. Einer der Blöcke muss zuerst gesprengt werden und der andere droppt dann

**Comment by TimK1998** [comment]
Alle gesprengten Blöcke werden gesavt und zurückgesetzt. Aber wenn ein Teil davon droppt wird das nicht getrackt. Und selbst wenn man das könnte hätte man selbiges Problem beim zusammenbauen. Platziert man nur das hintere Stück droppt es weil es unvollständig ist, selbiges mit dem Vorderen

**Comment by VMMarco** [comment]
Und was ist wenn man die Explosion selbst programmiert ? Also anstatt die blöcke weg zu sprengen einfach zu "Air" ändern und am ende halt wieder zu setzen das muss doch i.wie gehn auf alo und ethyron hats ja auch geklappt. Wenn der Fehler nie gefixt wird dauerts nich lang bis nur noch 20 leute spielen da viele keine lust haben jeden tag oder jeden zweiten ihre redstone Schaltung neu zu bauen das wird 100% fatal folgen haben Kamran war kurz davor zu quitten weil deren base halt unter der erde ist und ohne redstone Schaltung kann man halt nix unter der Erde bauen.
