### ISSUE TITLE
[BSkill] Belagerungsleiter baut sich nicht ab

### ISSUE THREAD

**Issue by oroshikirin11** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#675]
Belagerungsleiter baut sich nicht ab und zu nicht wieder ab

**Comment by Kyraja** [comment]
Konnten wir nicht reproduzieren, sonst wäre die Gilden Intervention. Gott habe sie seelig. Jetzt voll von unseren DEBUG leitern 👯
