### ISSUE TITLE
Seltsames Verhalten mit /g home

### ISSUE THREAD

**Issue by CubexsOne** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#676]
Man steht irgendwo und gibt `/g home` ein und landet aber am spawn.
Man stuckt fest und kann nichts mehr machen.

Nach einem Relogg sieht man kurz den Villager und dannach geht alles wieder.

P.S.: Es könnte sein das die Person die diesen Bug hat, Schaden austeilen kann.
( Spells etc. )

**Comment by Kyraja** [comment]
Können wir nicht reproduizieren. Werden wir im Auge behalten, ob es mit dem neuen EntitySystem nochmal aufritt
