### ISSUE TITLE
Chatfarbe von ContentCreate == Mods

### ISSUE THREAD

**Issue by CubexsOne** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#677]
Der ContentCreator hat das gleiche Lila wie Mods.
Alternativen:
- Mods -> grün
- ContentCreator -> türkis ( egal ob hell oder dunkel )
- ContentCreator -> grün

**Comment by Torre1234** [comment]
würde eher content creator gürn machen. blau lila und rot sind dann die Teamfarben und farblich näher bei einander

**Comment by Timkoe** [comment]
hab die Prio erhöht Content Creators sollten nicht dauerhaft wegen support zeug angeschrieben werden

**Comment by oroshikirin11** [comment]
Ist jetz dunkelgrün
