### ISSUE TITLE
Mount System bug

### ISSUE THREAD

**Issue by AioAioAio** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#680]
spieler ohne pferd können beim style ändern sign auf bestätigen drücken und verlieren dabei 500g

**Comment by AioAioAio** [comment]
Der Spieler Benfft hat dadurch 1000g verloren 
Vielleicht refunden?
er hat dies auch gemeldet

**Comment by Torre1234** [comment]
Kann ich machen wenn ich on komme, falls es schon wer gemacht hat bitte schließen. Aber wie lost muss man bitte sein, um das gleich 2 mal zu machen, wenn man garkein Pferd hat? :D
