### ISSUE TITLE
Improvement: Als 3. Partei im Gilden kampf das Non-Core Gebiet betreten dürfen

### ISSUE THREAD

**Issue by Timkoe** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#682]
Vorschlag:
Als 3. Partei im Gildenkampf das Non-Core Gebiet betreten dürfen

Ist zwar absolut sinnvoll dass in einem Gildenkampf keine 2 Gilden beim Angriff oder der Verteidigung kämpfen dürfen, aber ich fände es in Ordnung andere Gilden zumindest abfangen zu dürfen.
Dass 3. Parteien nichtmal das non core Gebiet betreten dürfen, benachteiligt aktuell eher die schwächeren Gilden, die meistens sich mit anderen Gilden verbünden um sich gegenseitig vor stärkeren zu schützen.

Der Gildenkampf an sich würde dadruch nicht gestört, da auf core Gebiet dann immernoch nur Angreifer und Verteidiger raufkönnen

**Comment by Kyraja** [comment]
@Timkoe Dann sollen sie einfach vor dem Non-Core Gebiet warten zum abfangen?

**Comment by Torre1234** [comment]
Wie abfangen, wenn man nach dem fight automatisch raus geportet wird? Fände das mit dem Randgebiet eig ganz nice, bisschen mehr PvP Aktion

**Comment by Kyraja** [comment]
@Torre1234 Das versteh ich ehrlich nicht.. DU hast recht die werden rausgeportet, dann kommen Sie ja auch nicht raus? Ich seh den benefit nicht für den Aufwand, den wir im Plugin betreiben müssten dafür das getroltl werden kann. Wurde das jemals derzeit so jemals probiert oder hatte das vor? Ich finde wir sollten uns auf Dinge konzentrieren die auch wichtig fürs Grundsystem ist und eher da unsere Programmierungszeit drauf legen.

Theoretische Anforderung würde ich erstmal auf Prio ZZZZZZZ stellen...

**Comment by Torre1234** [comment]
Ja, hat safe keine Prio, wenn es gehen würde hätten wir es heute bspw. bei Kamran genutzt, um vllt ein Paar von Requium weg zu farmen und damit der schächeren Gilde zu helfen, bevor der Angriff zu ist. Aber stimmt schon, gerade haben wir eher andere Baustellen

**Comment by Timkoe** [comment]
Es geht nicht daraum Leute nach dem raid abzusnacken.
Es geht darum Leute die sterben während dem raid abzufangen um den Nachschaub der Angreifer zu stören.
