### ISSUE TITLE
Improvement : Artefaktträger sollte kein pferd benutzen können

### ISSUE THREAD

**Issue by Tysaby** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#683]
Der Artefaktträger sollte kein pferd benutzen können da mit diesem das artefakt in kürzester zeit in sicherheit gebracht werden kann und es somit nahezu unmöglich wird den träger einzuholen. Dies scheint ja jedoch gewünscht zu sein da der artefaktträger debuffs erhält damit genau diese Möglichkeit besteht

**Comment by Torre1234** [comment]
Haben wir jetzt nicht eh eine deutlich größere range bei /horse , in welcher keine Gegner sein können? Meine wenn /horse geht, sollte auch schon fast /g home gehen, oder wie sind jeweils die Radien in denen keine Gegner sein dürfen?

**Comment by Tysaby** [comment]
Theoretisch kann man das pferd aber wieder beschwören bevor man in die ruine geht oder nicht? also daher arteträger direkt runter vom gaul
