### ISSUE TITLE
[MC EXP] Monster droppen keine Minecraft EXP wenn man nur mit Spells sie tötet

### ISSUE THREAD

**Issue by stefanomazz** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#686]
Wurde bisher nur mit Schneesturm getestet, wenn man KEINEN normalen Hit auf die Monster macht und Z.B. nur Schneesturm benutzt, droppen die Monster keine EXP.

**Comment by Timkoe** [comment]
Kann ich nicht reproduzieren
