### ISSUE TITLE
Gildenbelagerungs-Bugliste

### ISSUE THREAD

**Issue by Torre1234** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#687]
1.Verteidiger können während des /g fight Blöcke abbauen, auch bspw. Belagerungsleitern, sollte allgemein nicht gehen--->auch gm 2 setzen, asap fixen

2.Belagrungsskilll Cooldown mit BAC anzeigen lassen, aktuell nicht/ nur teilweise oder wenn kurz vor rdy

3.GM 2 für Angreifer wirkt auch in der Wildnis und teilweise nach dem der /g fight beendet ist noch

4.(Balancing) Belagerungsturm: entweder CD runter, mehr Module pro Turm aufbauen, Hitpoints erhöhen oder/und Abbauen nur mit Diamantspitzhacke ermöglichen. Aktuell viel zu schwach insgesamt

**Comment by Timkoe** [comment]
1. Blöcke der eigenen Base finde ich fine zumindest Knöpfe usw sollten gehen.
Belasgerungsobjekte der Angreifer sollten aber nicht abbaubar sein, wenn das nicht geht dann müssen wir abbauen an sich disablen und ausnahmen bei knöpfen etc machen

2. Gute Idee aber nicht so High Prio

3. Ist bekannt in seperater issue

4. CD kann  50% reduziert werden

**Comment by VMMarco** [comment]
1. In gesprengten Bereichen können keine Belagerungsleitern plaziert werden. (Interner Fehler meldung)

**Comment by Kyraja** [comment]
Getestet und ging einwandfrei....

--> CD reduziert, Fixed GM, Belagerungsturm um 2 Elemente erweitert.

**Comment by Timkoe** [comment]
Bitte KEINE weiteren Module auf dem B Turm das Stacking ist aktuell vieel zu einfach

**Comment by Torre1234** [comment]
Wenn man nicht verteidigt joa :D
Btw pls einfach gm2 für Verteidiger, Abbauen im /g fight ging auf alo nicht ohen Grund net, bis jz jeden 2t. Angriff leitern abgebaut worden, sollte einfach net gehen

**Comment by oroshikirin11** [comment]
Meiner Meinung nach sollten die Module des BTurms wieder auf den Standard Wert zurück geschraubt werden, es ist so einfach nurnoch Ethyron 2.0 für Bunker auf höheren Ebenen.
Belagerungsleitern / generell Belagerungsstrukturen sollen auch nicht von Spielern abgebaut werden können.

**Comment by Torre1234** [comment]
Auch die Base sollte man nicht umbauen können, einfach /gm 2. Decken Aufbauen für Free Eisspiegel/Arkaner, so viele Abusemöglichkeiten. Gidlensollten so bauen, dass sie zum verteidigen nicht nochmal live umbauen müssen

**Comment by Torre1234** [comment]
Und warum kein starker Bturm? Man kann ihn einfach Abbauen, bestraft nur Leute die in der Base hocken, aktiv Verteidigen heißt halt nicht nur vom turm spammen.
Sprengung und Obsibrecher sind aktuell noch heftiger, und da wollen wir Schaden noch nerfen?  Dann können wir auch gleich in die Bauregeln "Tower only" und "bloß nicht unterirdisch/unique" bauen schreiben :D
