### ISSUE TITLE
Verlorene Defense wird als verlorener Angriff angezeigt

### ISSUE THREAD

**Issue by Ricokoe** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#689]
Meine Gilde (Azeroth) hat vorhin eine Defense gegen Requium verloren, wurde aber als verlorener Angriff nicht Defense gewertet.

**Comment by Kyraja** [comment]
Ist falsch herum gedreht. Ist schon gefixt mit dem nächsten Patch
