### ISSUE TITLE
[Gfight] Schutzzeit funkt. immernoch nicht

### ISSUE THREAD

**Issue by oroshikirin11** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#695]
Falls das was im Changelog schon live ist:

Schutzzeit ab 0:00 funkt. nicht
Aktuell 1:00

**Comment by Timkoe** [comment]
Kann ich bestätigen

**Comment by Kyraja** [comment]
@oroshikirin11 Ich kann im code nicht feststelllen, woran es liegen soll.. daher bitte nochmal beobachten ggs. heute nacht, dass wir euch einen gfight drücken
