### ISSUE TITLE
Gewonnene Angriffe werden werden als Gewonnene Verteidigung angezeigt

### ISSUE THREAD

**Issue by Timkoe** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#696]
Found
Gewonnene Angriffe werden werden als Gewonnene Verteidigung angezeigt
(nachdem die Gilde einen vorherigen Angriff auf eine andere Gilde verloren hat)
Sieef griff Reckless and und verlor.
Danach griff Sieef  Leffotak an und gewann.
in den g info stats:
![2020-05-29_00 30 14](https://user-images.githubusercontent.com/55351056/83201583-17f5f880-a146-11ea-8978-8b40159880d6.png)

**Comment by Kyraja** [comment]
Ist bereits mit nächstne start gefixt
