### ISSUE TITLE
Tablist aktualisierung nicht ganz so aktuell

### ISSUE THREAD

**Issue by CubexsOne** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#697]
Siehe Screenshot:
Habe die Klasse gewechselt.

Wird vermutlich nur bei Login aktualisiert.
![YsfM7WdfY7SSaUtZJif2dg](https://user-images.githubusercontent.com/46932387/83201701-64413880-a146-11ea-82ce-752e73d53e39.png)

**Comment by Timkoe** [comment]
Low prio
