### ISSUE TITLE
Balancing: Schneesturm Range oder Damage sollte reduziert werden

### ISSUE THREAD

**Issue by Timkoe** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#700]

**Comment by Torre1234** [comment]
Würde alle Aoe's mit dem neuen Rüstungssystem verrechnen lassen, dann würde ich Skill balancing etwas nach hinten schieben. Gerade den Hexer treffen bspw. 25% weniger Schaden von Skills sehr hart, wenn wir dazu noch Flat DMG nerfen fühlt es sich sehr schwach an
