### ISSUE TITLE
Task: Enterhaken CD von 120s auf 60s reduzieren

### ISSUE THREAD

**Issue by Timkoe** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#702]

**Comment by Torre1234** [comment]
Bin ich auch für, dafür Manakosten erhöhen damit er im Combat nicht zu stark ist, bei Belagerungen ist er aktuell jedoch zu schwach.

Können wir die allgemeinene Balancing Anpassungen vllt. erst zusammen im Doc/ sonst wo festhalten und diskutieren ? Dann muss man nicht bei jedem Skill in nem Issue schreiben, zumal wir gerade ja eh ein größeres Update in der Richtung machen wollen.
