### ISSUE TITLE
Improvement: Blancing: Kampfrausch max. Heal von 250 HP auf 350 HP erhöhen

### ISSUE THREAD

**Issue by Timkoe** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#703]
Userfeedback:
Kampfrausch ist aktuell nutzlos und hat zu wenig impact im Kampf, Heilung ist kaum bemerkbar

-> Daher Heal erhöhen oder Wirkung auf den gegner hinzufügen.
Vorschlag: Heal von 250 -> 350 statt max. 5 Schläge maximum 7 Schläge

**Comment by Torre1234** [comment]
Ist ja bewusst nicht so stark wie der erste Heal, wäre komplett busted wenn du 2x 350 Heilen kannst als Klasse mit 2. meisten Hp, 2. Meisten Onhit und meisten AOE's. 
Man könnte Stärke 1 für bspw. 5s hinzufügen, mit Armor Buffs wird HP und damit auch Kampfrausch allerdings auch so schon stärker, weil HP "wertvoller" wird
