### ISSUE TITLE
Gildenkampf läuft ab, Lootzeit geht vorbei aber Angreifer werden nicht wegteleportiert und der Kampf endet nicht

### ISSUE THREAD

**Issue by Timkoe** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#708]
Angreifer stecken in der Base fest, keine Schutzzeit triggert 
und der Gildenkampf endet nicht

**Comment by Timkoe** [comment]
versuche es erneut zu reproduzieren

**Comment by Timkoe** [comment]
100% reproduzierbar

**Comment by Kamuuh** [comment]
Bei Fall Naughty(A) vs Reckless(V) wurden die Gstats von Reckless resettet. Gildenkampf endete nicht 10 Min nach Sieg von Naughty
