### ISSUE TITLE
[Guild] Mitgliedersteuer wird nicht abgezogen

### ISSUE THREAD

**Issue by stefanomazz** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#718]

**Comment by TimK1998** [comment]
Retest pls

**Comment by Timkoe** [comment]
bitte mehr info liefern @stefanomazz

**Comment by stefanomazz** [comment]
Wir haben zurzeit eine Mitgliedersteuer von 150g, die letzten Tage wurde nix von der Spielerbänken abgezogen.

@Timk1998 Ich schaue morgen ob es bei mir abgezogen wird.
