### ISSUE TITLE
Hinterhalt unsichtbarkeit löst sich nicht richtig auf

### ISSUE THREAD

**Issue by Tysaby** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#719]
Hinterhalt unsichtbarkeit löst sich nicht richtig auf. Weder wenn der anwender schaden austeilt noch wenn der Anwender schaden erhält

**Comment by Timkoe** [comment]
Hinterhalt 3s unsichtbarkeit sollen sich nicht auflösen
