### ISSUE TITLE
Megatask: Rüstungs & Balancing Rework

### ISSUE THREAD

**Issue by Timkoe** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#721]
**Neue Rüstungs & Enchantwerte:**
![grafik](https://user-images.githubusercontent.com/55351056/83327089-9c956380-a279-11ea-8914-aa30c006f177.png)

https://docs.google.com/spreadsheets/d/1FIsb7URs2RHjugSpKvk28jALiu9xWQQWepqJXiEhsZE/edit?usp=sharing

(wird im Konzept übernommen)

---------------------------------------- DONE START ----------------------------------------

**HP changes:**
Templer: -100HP -----------DONE
Barbar:-50 HP -----------DONE
Jäger:  insgesamt jetzt 1100 HP -----------DONE

**Balancing changes an bestehenden skills:**

Barbar:
Spalten: 
Ab jetzt Truedamage (Rüstungsdurchdringend)
-50 HP bei Einsatz des Skills
Aufstampfen:
Ab jetzt 130 DMG
Kampfrausch:
Stärke I 5s

Axtwurf: Slowness I 5s auf getroffenes Ziel --------------DONE

Schattenklinge:
Schattenstoss: = true damage (Rüstungsdurchddringend)
Enterhaken: CD auf 60s, (DONE) 
Manakosten: 100, Plattform soll 60s halten 

Dunkle Wiederkehr: Speed II für 3s bei erster Aktivierung, 150 HP Heal bei 2. Aktivierung

Hexer:
Zeitkrümmung: 120 DMG Dauer -5s, Levitation 2 -------------------- DONE
Blitzschlag: true Damage

Templer:
Glaubenskraft: +1 Radius Range ----------------DONE
Helfende Hand: -5s CD, Manakosten auf 40 ----------- DONE
Soll Debuffs vom Ziel entfernen

Waldläufer: 
Drachenpfeil: -150 statt -200 Self --------------------- DONE
Sprung auf 20s CD ---------------- DONE
Präzi: -50 flatdamage, und ab jetzt Truedamage 

-- Healskills von allen Klassen kosten keinen Slot mehr--

--------------------------------------- DONE END ----------------------------------

**Neue Skills:**

Barbar:
Level: 70:
Wutgriff:
Der Anwender hält das anvisierte Ziel und sich selbst fest (Slowness 4 5s) und verstummt sich selbst und das anvisierte Ziel (Beide können für 5s keine Skills einsetzen)
CD: 40s  Mana: 40 Range: 5

 Level 90: 
Unsterbliche Wut: 
Der Nutzer kann für 5 Sekunden nicht unter 100 HP fallenund erhält Stärke I,   Mana: 40, CD: 60s

Schattenklinge:
Level 70:
Kehlschnitt 150 DMG Verhindert den nächsten Skill des getroffenen Gegners  35 Mana 20s CD

Level: 90:
Schattenfall  negiert nächsten Fallschaden, 5 sekunden unsichtbarkeit und speed III nach Fall  40 Mana | 50s CD

Templer:
Level 70:
Segen: 
200 Heal 20s CD Auf Teammate, Mana: 25  

Level 90:
Anwender verleiht sich und Verbündeten Resistenz I für 8s
Resistenz 1 = + 25% mehr Rüstung
CD: 40s, Mana: 30

Hexer:
Level 70:
Manaextraktion:
Der Anwender stiehlt dem Gegner 40 Mana und richtet 100 Schaden an
Mana: 5, CD: 40s Range: 6 Blocks

Level 90:
Kettenblitze | nächsten 3 hits machen bonus 50 True Dmg, dieser springt auf den nächsten gegner(max 3 blöcke über, max 3 mal) 45s  45 Mana
(@TimK1998 wenn zu kompliziert bitte bescheid geben)
(angepasst)

Waldläufer:
Sprung kommt auf Level 20 -> Giftpfeil auf 30 -> Jagdinstinkt auf 70
Level: 0
Schnellschuss:
Neuer Standartskill, 5 sec Cd, Feuert direkt einen Pfeil in Blickrichtung für 150 DMG (leichter Knockback)  -> Linksklick mit dem Bogen
CD: 5, Mana: 5     Range: 25 Blocks (wenn möglich grade fliegen aka feuergeschoss)

Level 90:
Netzwurf:
Netzwurf |nächster Pfeil schießt netz, 3x3, 1 block hoch, bleibt 7 Sekunden   Range: 25 Blocks|  
CD: 45s Mana: 40

Änderungen werden noch im Konzept und Wiki übernommen
-- Bei Fragen bitte an mich oder Torre wenden --

Bitte abgeschlossene changes mit ----DONE markieren

**Comment by Torre1234** [comment]
Edit: Enchants
Protection: 1% pro Stufe, blockt jedlichen Schaden
ein Teil Prot IV =4%
komplette Prot IV=16%

**Comment by Timkoe** [comment]
Wutgriff, Mage lvl 70 neu und Kettenblitze angepasst @TimK1998

**Comment by Timkoe** [comment]
Hab alle meine Changes mit --------- DONE markiert

**Comment by Kyraja** [comment]
@TimK1998 Ist hier noch ein Doing?

**Comment by Torre1234** [comment]
kampfrausch gibt noch keine stärke
und axtwurf noch keinen slow
dunkle wiederkehr kein speed
