### ISSUE TITLE
Mit skill Schleichen kann man von Kampfzone zurück in Spawn

### ISSUE THREAD

**Issue by minecabl** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#722]
Wenn man Schleichen aktiv hat, wird man wegen den öfter auftretenden kurzen zurücksetzten manchmal nicht korrekt von der Border zurückgeworfen und kann so in den Spawn zurück.

**Comment by Kyraja** [comment]
Wüsste nicht wie wir das verhindern können... bis auf cd auf schleichen und das wäre kagge...
