### ISSUE TITLE
Improvement: Berufe

### ISSUE THREAD

**Issue by Torre1234** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#723]
Berufen minimale Statbonis geben, solange noch kein besseres Berufesystem da ist können wir so langzeit Anreize setzten, ohne dem Balancing zu schaden:
Bergarbeiter: alle 10 Level 5 HP, 50 HP auf 100
Grabenknecht: alle 10 Level 5 HP, 50 HP auf 100
Holzfäller: alle 10 Level 5 HP, 50 HP auf 100

Fischer: alle 10 Level 2.5 Mana, 25 Mana auf 100
Bauer. alle 10 Level 2.5 Mana, 25 Mana auf 100

max Gesamtboni:+150 HP, +50 Mana, wirft kein Balancing um aber ist nice to have

**Comment by TimK1998** [comment]
Tim willst du das nochmal überarbeiten? @Timkoe

**Comment by Timkoe** [comment]
Hab die werte nochmal hochgeschraubt @TimK1998
