### ISSUE TITLE
[Guild] /g kick SPIELERNAME geht nicht

### ISSUE THREAD

**Issue by stefanomazz** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#727]

**Comment by Kyraja** [comment]
Wird nicht gehen, da Befehle nur auf OnlineSpieler verwendet werden können. 
Daher bitte über Gilbenblock kicken.

**Comment by stefanomazz** [comment]
Kann trotz als Offizier aber niemanden über den Gildenblock kicken.
