### ISSUE TITLE
[KeepInventory] Überall kämpfen mit KeepInventory

### ISSUE THREAD

**Issue by oroshikirin11** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#731]
Überall kämpfen mit KeepInventory indem man das Arenasystem ausnutzt:

1. Man wirft ne Enderperle in die Luft (am besten in einem geladenen Gebiet)
2. Man nimmt während die Perle in der Luft ist schnell die Arenaanfrage an
3. Man teleportiert sich in die Arena und wird wieder raus tpt wegen der EPerle
4. Tada! KeepInventory ist da und man kann hingehen wohin man möchte.

**Comment by TimK1998** [comment]
-> Ban
