### ISSUE TITLE
[Guild] Spieler werden falsch angezeigt

### ISSUE THREAD

**Issue by stefanomazz** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#733]
![image](https://user-images.githubusercontent.com/61943468/83352213-4ba17000-a34a-11ea-94c4-28a89791d3ac.png)

**Comment by stefanomazz** [comment]
Bei TAB auch der Fehler

**Comment by Timkoe** [comment]
Inwiefern falsch angezeigt? @stefanomazz

**Comment by stefanomazz** [comment]
Siehst ja, die Namen sind nicht richtig bzw. ersetzt mit anderen Namen. Also der Spieler LeMockl aus meiner Gilde hat das Problem, Restart vom Client auch nix gebracht

**Comment by TimK1998** [comment]
Ist ganz sicher nicht von uns, die Tablist ist rein Vanilla
