### ISSUE TITLE
Bei Gfight zwischen Reckless(V)  und Naughty (A) Stats zurückgesetzt 

### ISSUE THREAD

**Issue by Kamuuh** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#735]
Bei Zerstörung des Gildenblocks von Reckless, wurden deren Gstats zurückgesetzt

**Comment by stefanomazz** [comment]
Also unsere Stats wurden nicht zurückgesetzt, bzw. der Fight läuft immer noch und der Angriff wurde noch nicht in die Stats hinzugefügt.
