### ISSUE TITLE
[Class] Man behält die Stats der alten Klasse on Classchange-

### ISSUE THREAD

**Issue by oroshikirin11** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#737]
Wenn man von einer Klasse auf die andere wechselt, behält man, wenn man nicht reloggt / nicht levelt die Stats der alten Klasse (HP ist 100% verifiziert)

Besonders schlimm ist es wenn man z.B einen 100er Templer hat und dann auf seinen 100er Schurken wechselt.
Man kann am Artefight teilnehmen mit den Krieger lvl 100 HP, obwohl man Schurke spielt.

**Comment by TimK1998** [comment]
#734
