### ISSUE TITLE
Eisgefängiss Blücke despawnen nicht immer

### ISSUE THREAD

**Issue by CubexsOne** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#740]
Wenn man Eisgefängniss macht, despawnen manchmal nicht alle Blöcke.

**Comment by minecabl** [comment]
Wenn man die Blöcke Sprengt, und diese Respawnen, despawnen sie nicht mehr.

**Comment by TimK1998** [comment]
Ist das die einzige Situation wo sie nicht mehr despawnen? @minecabl
