### ISSUE TITLE
Issues Megaupdate:

### ISSUE THREAD

**Issue by Timkoe** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#752]
Allgemein:
Rüstung blockt sämtlichen autohit schaden (Spieler mit rüstung erhalten nur noch skilldamage)
(konnten daher kein fight testen)
Protection enchant ignoriert True Damage (True Damage geht nicht durch Protection)

Bestehende skills:
- Blitzscvhlag is kein true dmg

Erschöpfen:
- Spieler mit Weakness können andere Spieler überhaupt nicht schlagen

Kettenblitz:
90 Bonus damags -> Der Damage wird aktuell nicht auf den Autohitschaden aufgerechnet sondern ersetzt ihn 
(Bei getroffenen Ziel mit Autohitdmg bei den restlichen ohne)

Netzwurf:
    -Bleibt permanent statt nur 7s
    -Ist oft nicht 3x3 auf Aufschlagsort sondern manche Spinnenweben verschieben sich nahc hinten
 - fliegt unabhänging von Blickrichtung immer gleich

Schnellschuss
- Spieler die Rüstung tragen kriegen keinen damage (die ohne schon)
- Der Damage ist nicht locked auf 120 
hat ein Waldläufer Power auf dem Bogen, wird der Damage ungewollt erhöht

**Comment by TimK1998** [comment]
1. Rüsting blockt sämtlichen Schaden: Ja das war ein Fail, ist jetzt fixed
2. Enchant soll True damage blocken: Wusste ich nicht, ich dachte true ist true und fertig. Habs jetzt mal eingebaut.
3. Blitzschlag kein true damage: Alle True damaage skills hatten kein True damage, ist jetzt fixed
4. Spieler mit Weakness... : Da müsst ihr euch was anderes überlegen. Das ist leider von Vanilla so. Mit Weakness macht man mit ner Sense gar keinen Schaden und deswegen passiert da gar nichts. Gibt leider keine Möglichkeit zu tracken, ob man ein Entity ohne Schaden linksklickt
5. Kettenblitz: buffed
6. Netzwurf. Hab das jetzt so geändert, dass man nen Pfeil schießt an dessen Aufschlagsort das Netz kommt. Ist besser zu kontrollieren und deutlich weniger buggy. Netzfalle verschwindet jetzt
7. Schnellschuss too much damage: Ja das ist in der tat so, ich weiß aber gearde auch keinen cleveren Weg das zu verhindern, muss da nochmal reinschauen. Zumindest dass die Enchants keine Wirkung haben sollte gehen, aber der Schaden den der PFeil macht wird vermutlich immer der eines vollgespannten Bogens (130dmg) sein.

**Comment by TimK1998** [comment]
Okay ja Schnellschuss ollte jetzt nur die 130 Dmg machen. Fixes sind live

**Comment by Timkoe** [comment]
2. Enchants sollen kein true Damage blocken, haben sie aber gestern getan soweit wir es sehen konnten

**Comment by Timkoe** [comment]
@TimK1998 
Weitere issues: Autohitskills können nicht gecastet werden -> Spieler besitzt keinen Skill mit dem Namen

**Comment by Timkoe** [comment]
./skill heal geht noch nicht
