### ISSUE TITLE
Skillchanges Megaupdate:

### ISSUE THREAD

**Issue by Timkoe** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#756]
Level 90:
Unsterbliche Wut:
- 5s Schwäche raus

Templer lvl 90:
statt erschöpfen:
Stahlrüstung:
Anwender verleiht sich und Verbündeten Resistenz I für 8s
Resistenz 1 = + 25% mehr Rüstung
CD: 40s, Mana: 30

**Comment by Kamuuh** [comment]
Wenn eine Netzfalle in eine Netzfalle geschossen wird spawnt die zweite erst wenn die erste verschwindet und ist Permanent und abbaubar

**Comment by badnumb3rs** [comment]
Hallo,
wir haben gestern ein paar Testduelle mit den neuen Skills gespielt und herausgefunden, dass der Jäger nur sehr schwer down zu bekommen ist.
Tim wollte den Schaden angepasst haben, was andere jedoch nicht so fanden. Meiner Meinung nach kann der Jäger, der ne hohe Mobility und viel Schaden hat nicht gleich viel Leben wie der Barbar haben. Ich würde das Leben des Jägers auf 1200 anpassen.
