### ISSUE TITLE
TP Fehlerhaft

### ISSUE THREAD

**Issue by badnumb3rs** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#761]
- TPaccept: Nun 1 Herz, 0 Mana, alle Skills auf CD und Nausea, Blindness und Slowness für 15 Sekunden

Also wenn ich mich zu jemanden Tpe dann, habe ich danach halbes leben, alle CDs, aber keine Mana. Diese regeniert auch nicht. Ausserdem fehlen noch die negativen Effekte

**Comment by TimK1998** [comment]
War zu dem Zeitpunkt noch nicht live
