### ISSUE TITLE
(Neues Update) Kettenblitze von Hexer geht nicht

### ISSUE THREAD

**Issue by Ricokoe** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#762]
Wenn ich Kettenblitze einsetzte passiert nichts

**Comment by Kyraja** [comment]
@Ricokoe Hast du die Monster angehittet? Ich glaube es war so gedachte, das du wenn du hittest der Damage "weiterspringt"

**Comment by Ricokoe** [comment]
Achso das wusste ich nicht stand nichts im Konzept dazu daher habe ich was falsches unter dem Skillnamen verstanden. Bug kann geclosed werden
