### ISSUE TITLE
Schadens/Verzauberungssystem: Sharpness und Power

### ISSUE THREAD

**Issue by Torre1234** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#763]
Sharpness und Power im Zuge des Balancing Patches angleichen und gleichzeitig relevant machen, da auch Armor und Prot gebufft wurde.
Beide sollten % Werte geben, da Flat bspw. bei Power auch Bowspamm zu stark gemacht hat und alle Klassen mit einem Power 4 Bogen diesen als viable Fernkampf abusen konnten, außerdem würde ein Flat Bonus bei Sharpness Klassen wie den Templer extrem stark machen.

Pro Power&Sharpness Stufe +10% Autohit DMG
Sharp 5= +50% (97,5 bei der Schattenklinge)
Power 5= +50%(195 beim Waldläufer)
Je nach aktuellen Stand beim Testen ggf. -10 Flat dmg beim Bogen, finaler Wert bei Power 5 wäre dann 180, jetziger liegt bei 175

Generell sollten Sharpness und Power sich lohnen und einen deutlich spürbaren Unterschied machen, über einen Buff von Sharpness können wir gleichzeitig Autohits relevanter machen, da aktuell vor Allem der Rechtsclick und einzelne Spells fights allein entscheiden.

**Comment by Timkoe** [comment]
[19:04] TimK1998: if (entry.getValue() == 1)
                            damageMultiplierAll += 0.15;
                        if (entry.getValue() == 2)
                            damageMultiplierAll += 0.225;
                        if (entry.getValue() == 3)
                            damageMultiplierAll += 0.30;
                        if (entry.getValue() == 4)
                            damageMultiplierAll += 0.35;
                        if (entry.getValue() == 5)
                            damageMultiplierAll += 0.40;
[19:04] TimK1998: Sharpness
[19:04] TimK1998: if(level == 1) calc.multiplyDamage(1.15);
            if(level == 2) calc.multiplyDamage(1.20);
            if(level == 3) calc.multiplyDamage(1.25);
            if(level == 4) calc.multiplyDamage(1.30);
            if(level == 5) calc.multiplyDamage(1.35);
[19:04] TimK1998: Power

**Comment by Timkoe** [comment]
Haben es getestet Spieler sind noch deutlich zu tanky wir müssen den enchant impact noch deutlicher erhöhen.

Power:
1 0.20
2 0.30
3 0.40
4 0.45
5 0.5

Sharp:
1 1.15
2 1.25
3 1.35
4: 1.45
5: 1.50
