### ISSUE TITLE
Forum Link in die Website einbauen, website link ins Forum einbauen

### ISSUE THREAD

**Issue by Timkoe** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#773]
Danke

**Comment by Torre1234** [comment]
+forum link ins wiki wäre auch nice to have

**Comment by CubexsOne** [comment]
Folgendes bereits erledigt
Link von:
- InfoPage -> Forum
- Wiki -> Forum
- Forum -> Wiki
