### ISSUE TITLE
Gilden Core Gebiet debuff bei Nachtschutz & Gilde Online

### ISSUE THREAD

**Issue by CubexsOne** [Lost-Kingdoms/Lost-Kingdoms-IssueTracker#807]
Ich wurde gefragt ob es gewollt ist, wenn der Nachtschutz aktiv ist, aber die Gilde online, dass es keine Debuffs auf dem Coregebiet gibt.

Kenne die Antwort hierauf nicht, daher das Ticket.

**Comment by Timkoe** [comment]
Finde ich ok, da die Gilde nicht wehrlos ist wenn sie als Online zählt.
